# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateOwnerParser do
  @moduledoc """
  Parser for auth.create_owner stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateOwnerModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateOwnerModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_owner returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([create_owner]) do
    {:ok, %AuthCreateOwnerModel{
      create_owner: create_owner,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_owner result")
    {:error, :invalid_row}
  end
end