# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthFilterAccessibleResourcesParser do
  @moduledoc """
  Parser for auth.filter_accessible_resources stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthFilterAccessibleResourcesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthFilterAccessibleResourcesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure filter_accessible_resources returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([filter_accessible_resources]) do
    {:ok, %AuthFilterAccessibleResourcesModel{
      filter_accessible_resources: filter_accessible_resources,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in filter_accessible_resources result")
    {:error, :invalid_row}
  end
end