# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserAssignedPermissionsParser do
  @moduledoc """
  Parser for auth.get_user_assigned_permissions stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserAssignedPermissionsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserAssignedPermissionsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_user_assigned_permissions returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([permissions, perm_set_title, perm_set_id, perm_set_code, assignment_id, user_group_id]) do
    {:ok, %AuthGetUserAssignedPermissionsModel{
      permissions: permissions,
      perm_set_title: perm_set_title,
      perm_set_id: perm_set_id,
      perm_set_code: perm_set_code,
      assignment_id: assignment_id,
      user_group_id: user_group_id,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_assigned_permissions result")
    {:error, :invalid_row}
  end
end