# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateProviderParser do
  @moduledoc """
  Parser for auth.create_provider stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateProviderModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateProviderModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_provider returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([create_provider]) do
    {:ok, %AuthCreateProviderModel{
      create_provider: create_provider,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_provider result")
    {:error, :invalid_row}
  end
end