# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGenerateApiKeyUsernameParser do
  @moduledoc """
  Parser for auth.generate_api_key_username stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGenerateApiKeyUsernameModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGenerateApiKeyUsernameModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure generate_api_key_username returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([generate_api_key_username]) do
    {:ok, %AuthGenerateApiKeyUsernameModel{
      generate_api_key_username: generate_api_key_username,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in generate_api_key_username result")
    {:error, :invalid_row}
  end
end