# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthSearchPermSetsParser do
  @moduledoc """
  Parser for auth.search_perm_sets stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthSearchPermSetsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthSearchPermSetsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "search_perm_sets",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([perm_set_id, title, code, is_system, is_assignable, permission_count, total_items]) do
    {:ok, %AuthSearchPermSetsModel{
      perm_set_id: perm_set_id,
      title: title,
      code: code,
      is_system: is_system,
      is_assignable: is_assignable,
      permission_count: permission_count,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_perm_sets result")
    {:error, :invalid_row}
  end
end