# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthAddPermSetPermissionsParser do
  @moduledoc """
  Parser for auth.add_perm_set_permissions stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthAddPermSetPermissionsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthAddPermSetPermissionsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "add_perm_set_permissions",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([perm_set_id, perm_set_code, permission_id, permission_code]) do
    {:ok, %AuthAddPermSetPermissionsModel{
      perm_set_id: perm_set_id,
      perm_set_code: perm_set_code,
      permission_id: permission_id,
      permission_code: permission_code,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in add_perm_set_permissions result")
    {:error, :invalid_row}
  end
end