# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetTenantUsersParser do
  @moduledoc """
  Parser for auth.get_tenant_users stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetTenantUsersModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetTenantUsersModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_tenant_users",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_id, username, display_name, user_groups]) do
    {:ok, %AuthGetTenantUsersModel{
      user_id: user_id,
      username: username,
      display_name: display_name,
      user_groups: user_groups,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_tenant_users result")
    {:error, :invalid_row}
  end
end