# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthUpdateTenantParser do
  @moduledoc """
  Parser for auth.update_tenant stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthUpdateTenantModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthUpdateTenantModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure update_tenant: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([tenant_id, uuid, title, code, is_removable, is_assignable, access_type_code, is_default]) do
    {:ok, %AuthUpdateTenantModel{
      tenant_id: tenant_id,
      uuid: uuid,
      title: title,
      code: code,
      is_removable: is_removable,
      is_assignable: is_assignable,
      access_type_code: access_type_code,
      is_default: is_default,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in update_tenant result")
    {:error, :invalid_row}
  end
end