# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthEnsureUserGroupMappingParser do
  @moduledoc """
  Parser for auth.ensure_user_group_mapping stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthEnsureUserGroupMappingModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthEnsureUserGroupMappingModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure ensure_user_group_mapping: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_group_mapping_id, user_group_id, is_new]) do
    {:ok, %AuthEnsureUserGroupMappingModel{
      user_group_mapping_id: user_group_mapping_id,
      user_group_id: user_group_id,
      is_new: is_new,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_user_group_mapping result")
    {:error, :invalid_row}
  end
end