# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthDeleteUserInfoParser do
  @moduledoc """
  Parser for auth.delete_user_info stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthDeleteUserInfoModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthDeleteUserInfoModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure delete_user_info: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_id, username]) do
    {:ok, %AuthDeleteUserInfoModel{
      user_id: user_id,
      username: username,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in delete_user_info result")
    {:error, :invalid_row}
  end
end