# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateExternalUserGroupParser do
  @moduledoc """
  Parser for auth.create_external_user_group stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateExternalUserGroupModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateExternalUserGroupModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure create_external_user_group: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([create_external_user_group]) do
    {:ok, %AuthCreateExternalUserGroupModel{
      create_external_user_group: create_external_user_group,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_external_user_group result")
    {:error, :invalid_row}
  end
end