# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthSearchUsersParser do
  @moduledoc """
  Parser for auth.search_users stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthSearchUsersModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthSearchUsersModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure search_users: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_id, code, uuid, username, email, display_name, user_type_code, is_active, is_locked, total_items]) do
    {:ok, %AuthSearchUsersModel{
      user_id: user_id,
      code: code,
      uuid: uuid,
      username: username,
      email: email,
      display_name: display_name,
      user_type_code: user_type_code,
      is_active: is_active,
      is_locked: is_locked,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_users result")
    {:error, :invalid_row}
  end
end