# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthSearchUserEventsParser do
  @moduledoc """
  Parser for auth.search_user_events stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthSearchUserEventsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthSearchUserEventsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure search_user_events: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_event_id, event_type_code, requester_user_id, requester_username, target_user_id, target_username, target_user_oid, request_context, event_data, correlation_id, created_at, created_by, total_items]) do
    {:ok, %AuthSearchUserEventsModel{
      user_event_id: user_event_id,
      event_type_code: event_type_code,
      requester_user_id: requester_user_id,
      requester_username: requester_username,
      target_user_id: target_user_id,
      target_username: target_username,
      target_user_oid: target_user_oid,
      request_context: request_context,
      event_data: event_data,
      correlation_id: correlation_id,
      created_at: created_at,
      created_by: created_by,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_user_events result")
    {:error, :invalid_row}
  end
end