# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthDeleteProviderParser do
  @moduledoc """
  Parser for auth.delete_provider stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthDeleteProviderModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthDeleteProviderModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure delete_provider returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([delete_provider]) do
    {:ok, %AuthDeleteProviderModel{
      delete_provider: delete_provider,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in delete_provider result")
    {:error, :invalid_row}
  end
end