# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserGroupsToSyncParser do
  @moduledoc """
  Parser for auth.get_user_groups_to_sync stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserGroupsToSyncModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserGroupsToSyncModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_user_groups_to_sync",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_group_id, user_group_mapping_id, title, code, provider_code, mapped_object_id, mapped_object_name]) do
    {:ok, %AuthGetUserGroupsToSyncModel{
      user_group_id: user_group_id,
      user_group_mapping_id: user_group_mapping_id,
      title: title,
      code: code,
      provider_code: provider_code,
      mapped_object_id: mapped_object_id,
      mapped_object_name: mapped_object_name,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_groups_to_sync result")
    {:error, :invalid_row}
  end
end