# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCanManageUserGroupParser do
  @moduledoc """
  Parser for auth.can_manage_user_group stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCanManageUserGroupModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCanManageUserGroupModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure can_manage_user_group returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([can_manage_user_group]) do
    {:ok, %AuthCanManageUserGroupModel{
      can_manage_user_group: can_manage_user_group,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in can_manage_user_group result")
    {:error, :invalid_row}
  end
end