# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateUserGroupParser do
  @moduledoc """
  Parser for auth.create_user_group stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateUserGroupModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateUserGroupModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "create_user_group",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([create_user_group]) do
    {:ok, %AuthCreateUserGroupModel{
      create_user_group: create_user_group,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_user_group result")
    {:error, :invalid_row}
  end
end