# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthSearchTenantsParser do
  @moduledoc """
  Parser for auth.search_tenants stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthSearchTenantsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthSearchTenantsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure search_tenants returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([tenant_id, uuid, title, code, is_removable, is_assignable, total_items]) do
    {:ok, %AuthSearchTenantsModel{
      tenant_id: tenant_id,
      uuid: uuid,
      title: title,
      code: code,
      is_removable: is_removable,
      is_assignable: is_assignable,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_tenants result")
    {:error, :invalid_row}
  end
end