# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthIsGroupMemberParser do
  @moduledoc """
  Parser for auth.is_group_member stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthIsGroupMemberModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthIsGroupMemberModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "is_group_member",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([is_group_member]) do
    {:ok, %AuthIsGroupMemberModel{
      is_group_member: is_group_member,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in is_group_member result")
    {:error, :invalid_row}
  end
end