# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateMfaChallengeParser do
  @moduledoc """
  Parser for auth.create_mfa_challenge stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateMfaChallengeModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateMfaChallengeModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_mfa_challenge returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([token_uid, expires_at]) do
    {:ok, %AuthCreateMfaChallengeModel{
      token_uid: token_uid,
      expires_at: expires_at,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_mfa_challenge result")
    {:error, :invalid_row}
  end
end