# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthAcceptInvitationParser do
  @moduledoc """
  Parser for auth.accept_invitation stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthAcceptInvitationModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthAcceptInvitationModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure accept_invitation returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([invitation_action_id, action_type_code, executor_code, sequence, payload]) do
    {:ok, %AuthAcceptInvitationModel{
      invitation_action_id: invitation_action_id,
      action_type_code: action_type_code,
      executor_code: executor_code,
      sequence: sequence,
      payload: payload,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in accept_invitation result")
    {:error, :invalid_row}
  end
end