# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthEnsureUserGroupMappingsParser do
  @moduledoc """
  Parser for auth.ensure_user_group_mappings stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthEnsureUserGroupMappingsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthEnsureUserGroupMappingsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure ensure_user_group_mappings returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, user_group_mapping_id, user_group_id, provider_code, mapped_object_id, mapped_object_name, mapped_role]) do
    {:ok, %AuthEnsureUserGroupMappingsModel{
      created_at: created_at,
      created_by: created_by,
      user_group_mapping_id: user_group_mapping_id,
      user_group_id: user_group_id,
      provider_code: provider_code,
      mapped_object_id: mapped_object_id,
      mapped_object_name: mapped_object_name,
      mapped_role: mapped_role,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_user_group_mappings result")
    {:error, :invalid_row}
  end
end