# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserGroupMembersParser do
  @moduledoc """
  Parser for auth.get_user_group_members stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserGroupMembersModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserGroupMembersModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_user_group_members",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created, created_by, member_id, member_type_code, user_id, user_display_name, user_is_system, user_is_active, user_is_locked, mapping_id, mapping_mapped_object_name, mapping_provider_code]) do
    {:ok, %AuthGetUserGroupMembersModel{
      created: created,
      created_by: created_by,
      member_id: member_id,
      member_type_code: member_type_code,
      user_id: user_id,
      user_display_name: user_display_name,
      user_is_system: user_is_system,
      user_is_active: user_is_active,
      user_is_locked: user_is_locked,
      mapping_id: mapping_id,
      mapping_mapped_object_name: mapping_mapped_object_name,
      mapping_provider_code: mapping_provider_code,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_group_members result")
    {:error, :invalid_row}
  end
end