# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserAuditTrailParser do
  @moduledoc """
  Parser for auth.get_user_audit_trail stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserAuditTrailModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserAuditTrailModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_user_audit_trail returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([source, event_id, event_type_code, event_category, message, request_context, event_data, correlation_id, created_at, created_by, total_items]) do
    {:ok, %AuthGetUserAuditTrailModel{
      source: source,
      event_id: event_id,
      event_type_code: event_type_code,
      event_category: event_category,
      message: message,
      request_context: request_context,
      event_data: event_data,
      correlation_id: correlation_id,
      created_at: created_at,
      created_by: created_by,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_audit_trail result")
    {:error, :invalid_row}
  end
end