# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetSecurityEventsParser do
  @moduledoc """
  Parser for auth.get_security_events stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetSecurityEventsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetSecurityEventsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_security_events returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([source, event_type_code, requester_user_id, requester_username, target_user_id, target_username, request_context, event_data, correlation_id, created_at, total_items]) do
    {:ok, %AuthGetSecurityEventsModel{
      source: source,
      event_type_code: event_type_code,
      requester_user_id: requester_user_id,
      requester_username: requester_username,
      target_user_id: target_user_id,
      target_username: target_username,
      request_context: request_context,
      event_data: event_data,
      correlation_id: correlation_id,
      created_at: created_at,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_security_events result")
    {:error, :invalid_row}
  end
end