# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthUpdateUserPasswordParser do
  @moduledoc """
  Parser for auth.update_user_password stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthUpdateUserPasswordModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthUpdateUserPasswordModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "update_user_password",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_id, provider_code, provider_uid]) do
    {:ok, %AuthUpdateUserPasswordModel{
      user_id: user_id,
      provider_code: provider_code,
      provider_uid: provider_uid,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in update_user_password result")
    {:error, :invalid_row}
  end
end