# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserAccessibleResourcesParser do
  @moduledoc """
  Parser for auth.get_user_accessible_resources stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserAccessibleResourcesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserAccessibleResourcesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_user_accessible_resources returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([resource_id, resource_path, access_flags, source]) do
    {:ok, %AuthGetUserAccessibleResourcesModel{
      resource_id: resource_id,
      resource_path: resource_path,
      access_flags: access_flags,
      source: source,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_accessible_resources result")
    {:error, :invalid_row}
  end
end