# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthDeleteResourceRoleParser do
  @moduledoc """
  Parser for auth.delete_resource_role stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthDeleteResourceRoleModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthDeleteResourceRoleModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure delete_resource_role returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([delete_resource_role]) do
    {:ok, %AuthDeleteResourceRoleModel{
      delete_resource_role: delete_resource_role,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in delete_resource_role result")
    {:error, :invalid_row}
  end
end