# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGenerateApiSecretHashParser do
  @moduledoc """
  Parser for auth.generate_api_secret_hash stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGenerateApiSecretHashModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGenerateApiSecretHashModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure generate_api_secret_hash returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([generate_api_secret_hash]) do
    {:ok, %AuthGenerateApiSecretHashModel{
      generate_api_secret_hash: generate_api_secret_hash,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in generate_api_secret_hash result")
    {:error, :invalid_row}
  end
end