# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthLockUserGroupParser do
  @moduledoc """
  Parser for auth.lock_user_group stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthLockUserGroupModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthLockUserGroupModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure lock_user_group: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_group_id, is_active, is_assignable, updated_at, updated_by]) do
    {:ok, %AuthLockUserGroupModel{
      user_group_id: user_group_id,
      is_active: is_active,
      is_assignable: is_assignable,
      updated_at: updated_at,
      updated_by: updated_by,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in lock_user_group result")
    {:error, :invalid_row}
  end
end