# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthDisableProviderParser do
  @moduledoc """
  Parser for auth.disable_provider stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthDisableProviderModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthDisableProviderModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure disable_provider returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([disable_provider]) do
    {:ok, %AuthDisableProviderModel{
      disable_provider: disable_provider,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in disable_provider result")
    {:error, :invalid_row}
  end
end