# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserByEmailForAuthenticationParser do
  @moduledoc """
  Parser for auth.get_user_by_email_for_authentication stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserByEmailForAuthenticationModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserByEmailForAuthenticationModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_user_by_email_for_authentication: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_id, code, uuid, username, email, display_name, provider, password_hash, password_salt]) do
    {:ok, %AuthGetUserByEmailForAuthenticationModel{
      user_id: user_id,
      code: code,
      uuid: uuid,
      username: username,
      email: email,
      display_name: display_name,
      provider: provider,
      password_hash: password_hash,
      password_salt: password_salt,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_by_email_for_authentication result")
    {:error, :invalid_row}
  end
end