# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthAddUserToDefaultGroupsParser do
  @moduledoc """
  Parser for auth.add_user_to_default_groups stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthAddUserToDefaultGroupsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthAddUserToDefaultGroupsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "add_user_to_default_groups",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_id, user_group_id, user_group_code, user_group_title]) do
    {:ok, %AuthAddUserToDefaultGroupsModel{
      user_id: user_id,
      user_group_id: user_group_id,
      user_group_code: user_group_code,
      user_group_title: user_group_title,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in add_user_to_default_groups result")
    {:error, :invalid_row}
  end
end