# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthUpdateUserDataParser do
  @moduledoc """
  Parser for auth.update_user_data stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthUpdateUserDataModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthUpdateUserDataModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure update_user_data returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_id, user_data_id]) do
    {:ok, %AuthUpdateUserDataModel{
      user_id: user_id,
      user_data_id: user_data_id,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in update_user_data result")
    {:error, :invalid_row}
  end
end