# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetResourceGrantsParser do
  @moduledoc """
  Parser for auth.get_resource_grants stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetResourceGrantsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetResourceGrantsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_resource_grants: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([resource_access_id, user_id, user_display_name, user_group_id, group_title, access_flag, is_deny, granted_by, granted_by_name, created_at]) do
    {:ok, %AuthGetResourceGrantsModel{
      resource_access_id: resource_access_id,
      user_id: user_id,
      user_display_name: user_display_name,
      user_group_id: user_group_id,
      group_title: group_title,
      access_flag: access_flag,
      is_deny: is_deny,
      granted_by: granted_by,
      granted_by_name: granted_by_name,
      created_at: created_at,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_resource_grants result")
    {:error, :invalid_row}
  end
end