# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGrantResourceAccessParser do
  @moduledoc """
  Parser for auth.grant_resource_access stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGrantResourceAccessModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGrantResourceAccessModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure grant_resource_access: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([resource_access_id, access_flag]) do
    {:ok, %AuthGrantResourceAccessModel{
      resource_access_id: resource_access_id,
      access_flag: access_flag,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in grant_resource_access result")
    {:error, :invalid_row}
  end
end