# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetOutboundApiKeyByIdParser do
  @moduledoc """
  Parser for auth.get_outbound_api_key_by_id stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetOutboundApiKeyByIdModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetOutboundApiKeyByIdModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_outbound_api_key_by_id: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([api_key_id, api_key, title, description, service_code, service_url, extra_data, expire_at, notification_email, created_at, updated_at]) do
    {:ok, %AuthGetOutboundApiKeyByIdModel{
      api_key_id: api_key_id,
      api_key: api_key,
      title: title,
      description: description,
      service_code: service_code,
      service_url: service_url,
      extra_data: extra_data,
      expire_at: expire_at,
      notification_email: notification_email,
      created_at: created_at,
      updated_at: updated_at,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_outbound_api_key_by_id result")
    {:error, :invalid_row}
  end
end