# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserDataParser do
  @moduledoc """
  Parser for auth.get_user_data stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserDataModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserDataModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_user_data",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, updated_at, updated_by, user_data_id, user_id, first_name, middle_name, last_name, nrm_search_data]) do
    {:ok, %AuthGetUserDataModel{
      created_at: created_at,
      created_by: created_by,
      updated_at: updated_at,
      updated_by: updated_by,
      user_data_id: user_data_id,
      user_id: user_id,
      first_name: first_name,
      middle_name: middle_name,
      last_name: last_name,
      nrm_search_data: nrm_search_data,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_data result")
    {:error, :invalid_row}
  end
end