# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserAvailableTenantsParser do
  @moduledoc """
  Parser for auth.get_user_available_tenants stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserAvailableTenantsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserAvailableTenantsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_user_available_tenants",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([tenant_id, tenant_uuid, tenant_code, tenant_title, tenant_is_default]) do
    {:ok, %AuthGetUserAvailableTenantsModel{
      tenant_id: tenant_id,
      tenant_uuid: tenant_uuid,
      tenant_code: tenant_code,
      tenant_title: tenant_title,
      tenant_is_default: tenant_is_default,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_available_tenants result")
    {:error, :invalid_row}
  end
end