# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGenerateApiSecretParser do
  @moduledoc """
  Parser for auth.generate_api_secret stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGenerateApiSecretModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGenerateApiSecretModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure generate_api_secret: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([generate_api_secret]) do
    {:ok, %AuthGenerateApiSecretModel{
      generate_api_secret: generate_api_secret,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in generate_api_secret result")
    {:error, :invalid_row}
  end
end