# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetPermSetsParser do
  @moduledoc """
  Parser for auth.get_perm_sets stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetPermSetsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetPermSetsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_perm_sets: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([perm_set_id, title, code, is_system, is_assignable, permissions, source]) do
    {:ok, %AuthGetPermSetsModel{
      perm_set_id: perm_set_id,
      title: title,
      code: code,
      is_system: is_system,
      is_assignable: is_assignable,
      permissions: permissions,
      source: source,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_perm_sets result")
    {:error, :invalid_row}
  end
end