# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetTenantGroupsParser do
  @moduledoc """
  Parser for auth.get_tenant_groups stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetTenantGroupsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetTenantGroupsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_tenant_groups: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_group_id, group_code, group_title, is_external, is_assignable, is_active, members_count]) do
    {:ok, %AuthGetTenantGroupsModel{
      user_group_id: user_group_id,
      group_code: group_code,
      group_title: group_title,
      is_external: is_external,
      is_assignable: is_assignable,
      is_active: is_active,
      members_count: members_count,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_tenant_groups result")
    {:error, :invalid_row}
  end
end