# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetResourceRoleFlagsParser do
  @moduledoc """
  Parser for auth.get_resource_role_flags stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetResourceRoleFlagsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetResourceRoleFlagsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_resource_role_flags: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([get_resource_role_flags]) do
    {:ok, %AuthGetResourceRoleFlagsModel{
      get_resource_role_flags: get_resource_role_flags,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_resource_role_flags result")
    {:error, :invalid_row}
  end
end