# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthDeleteOutboundApiKeyParser do
  @moduledoc """
  Parser for auth.delete_outbound_api_key stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthDeleteOutboundApiKeyModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthDeleteOutboundApiKeyModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "delete_outbound_api_key",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([api_key_id, service_code]) do
    {:ok, %AuthDeleteOutboundApiKeyModel{
      api_key_id: api_key_id,
      service_code: service_code,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in delete_outbound_api_key result")
    {:error, :invalid_row}
  end
end