# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthUnassignPermissionParser do
  @moduledoc """
  Parser for auth.unassign_permission stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthUnassignPermissionModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthUnassignPermissionModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "unassign_permission",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, assignment_id, tenant_id, user_group_id, user_id, perm_set_id, permission_id]) do
    {:ok, %AuthUnassignPermissionModel{
      created_at: created_at,
      created_by: created_by,
      assignment_id: assignment_id,
      tenant_id: tenant_id,
      user_group_id: user_group_id,
      user_id: user_id,
      perm_set_id: perm_set_id,
      permission_id: permission_id,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in unassign_permission result")
    {:error, :invalid_row}
  end
end