# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetAllPermissionsParser do
  @moduledoc """
  Parser for auth.get_all_permissions stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetAllPermissionsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetAllPermissionsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_all_permissions",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([permission_id, is_assignable, title, code, full_code, has_children, short_code]) do
    {:ok, %AuthGetAllPermissionsModel{
      permission_id: permission_id,
      is_assignable: is_assignable,
      title: title,
      code: code,
      full_code: full_code,
      has_children: has_children,
      short_code: short_code,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_all_permissions result")
    {:error, :invalid_row}
  end
end