# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthEnableProviderParser do
  @moduledoc """
  Parser for auth.enable_provider stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthEnableProviderModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthEnableProviderModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure enable_provider: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([enable_provider]) do
    {:ok, %AuthEnableProviderModel{
      enable_provider: enable_provider,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in enable_provider result")
    {:error, :invalid_row}
  end
end