# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateUserTenantPreferencesParser do
  @moduledoc """
  Parser for auth.create_user_tenant_preferences stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateUserTenantPreferencesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateUserTenantPreferencesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_user_tenant_preferences returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by]) do
    {:ok, %AuthCreateUserTenantPreferencesModel{
      created_at: created_at,
      created_by: created_by,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_user_tenant_preferences result")
    {:error, :invalid_row}
  end
end