# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserAssignedGroupsParser do
  @moduledoc """
  Parser for auth.get_user_assigned_groups stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserAssignedGroupsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserAssignedGroupsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_user_assigned_groups",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_group_member_id, user_group_id, user_group_code, user_group_title, user_group_member_type_code, user_group_mapping_id]) do
    {:ok, %AuthGetUserAssignedGroupsModel{
      user_group_member_id: user_group_member_id,
      user_group_id: user_group_id,
      user_group_code: user_group_code,
      user_group_title: user_group_title,
      user_group_member_type_code: user_group_member_type_code,
      user_group_mapping_id: user_group_mapping_id,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_assigned_groups result")
    {:error, :invalid_row}
  end
end