# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserPreferencesParser do
  @moduledoc """
  Parser for auth.get_user_preferences stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserPreferencesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserPreferencesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_user_preferences",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([get_user_preferences]) do
    {:ok, %AuthGetUserPreferencesModel{
      get_user_preferences: get_user_preferences,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_preferences result")
    {:error, :invalid_row}
  end
end