# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateResourceRoleParser do
  @moduledoc """
  Parser for auth.create_resource_role stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateResourceRoleModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateResourceRoleModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_resource_role returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, resource_type, title, description, is_active, source, access_flags]) do
    {:ok, %AuthCreateResourceRoleModel{
      code: code,
      resource_type: resource_type,
      title: title,
      description: description,
      is_active: is_active,
      source: source,
      access_flags: access_flags,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_resource_role result")
    {:error, :invalid_row}
  end
end