# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserGroupByIdParser do
  @moduledoc """
  Parser for auth.get_user_group_by_id stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserGroupByIdModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserGroupByIdModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_user_group_by_id returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_group_id, tenant_id, title, code, is_system, is_external, is_assignable, is_active, is_default]) do
    {:ok, %AuthGetUserGroupByIdModel{
      user_group_id: user_group_id,
      tenant_id: tenant_id,
      title: title,
      code: code,
      is_system: is_system,
      is_external: is_external,
      is_assignable: is_assignable,
      is_active: is_active,
      is_default: is_default,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_group_by_id result")
    {:error, :invalid_row}
  end
end