# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthHasOwnerParser do
  @moduledoc """
  Parser for auth.has_owner stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthHasOwnerModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthHasOwnerModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure has_owner returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([has_owner]) do
    {:ok, %AuthHasOwnerModel{
      has_owner: has_owner,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in has_owner result")
    {:error, :invalid_row}
  end
end