# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthPurgeTenantParser do
  @moduledoc """
  Parser for auth.purge_tenant stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthPurgeTenantModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthPurgeTenantModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure purge_tenant returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([tenant_id, uuid, code]) do
    {:ok, %AuthPurgeTenantModel{
      tenant_id: tenant_id,
      uuid: uuid,
      code: code,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in purge_tenant result")
    {:error, :invalid_row}
  end
end