# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateApiKeyParser do
  @moduledoc """
  Parser for auth.create_api_key stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateApiKeyModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateApiKeyModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "create_api_key",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([api_key_id, api_key, api_secret]) do
    {:ok, %AuthCreateApiKeyModel{
      api_key_id: api_key_id,
      api_key: api_key,
      api_secret: api_secret,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_api_key result")
    {:error, :invalid_row}
  end
end