# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthEnsureInvitationTemplatesParser do
  @moduledoc """
  Parser for auth.ensure_invitation_templates stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthEnsureInvitationTemplatesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthEnsureInvitationTemplatesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure ensure_invitation_templates: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, updated_at, updated_by, template_id, tenant_id, code, title, description, is_active, default_message, source]) do
    {:ok, %AuthEnsureInvitationTemplatesModel{
      created_at: created_at,
      created_by: created_by,
      updated_at: updated_at,
      updated_by: updated_by,
      template_id: template_id,
      tenant_id: tenant_id,
      code: code,
      title: title,
      description: description,
      is_active: is_active,
      default_message: default_message,
      source: source,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_invitation_templates result")
    {:error, :invalid_row}
  end
end