# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthUpdateOutboundApiKeyParser do
  @moduledoc """
  Parser for auth.update_outbound_api_key stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthUpdateOutboundApiKeyModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthUpdateOutboundApiKeyModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure update_outbound_api_key returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([api_key_id, title, description, service_url, extra_data, expire_at, notification_email]) do
    {:ok, %AuthUpdateOutboundApiKeyModel{
      api_key_id: api_key_id,
      title: title,
      description: description,
      service_url: service_url,
      extra_data: extra_data,
      expire_at: expire_at,
      notification_email: notification_email,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in update_outbound_api_key result")
    {:error, :invalid_row}
  end
end