# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateInvitationFromTemplateParser do
  @moduledoc """
  Parser for auth.create_invitation_from_template stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateInvitationFromTemplateModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateInvitationFromTemplateModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_invitation_from_template returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([invitation_id, uuid, on_create_actions]) do
    {:ok, %AuthCreateInvitationFromTemplateModel{
      invitation_id: invitation_id,
      uuid: uuid,
      on_create_actions: on_create_actions,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_invitation_from_template result")
    {:error, :invalid_row}
  end
end