# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthIsMfaRequiredParser do
  @moduledoc """
  Parser for auth.is_mfa_required stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthIsMfaRequiredModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthIsMfaRequiredModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure is_mfa_required: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([is_mfa_required]) do
    {:ok, %AuthIsMfaRequiredModel{
      is_mfa_required: is_mfa_required,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in is_mfa_required result")
    {:error, :invalid_row}
  end
end