# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthUpdateProviderParser do
  @moduledoc """
  Parser for auth.update_provider stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthUpdateProviderModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthUpdateProviderModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "update_provider",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([update_provider]) do
    {:ok, %AuthUpdateProviderModel{
      update_provider: update_provider,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in update_provider result")
    {:error, :invalid_row}
  end
end