# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetEffectiveGroupPermissionsParser do
  @moduledoc """
  Parser for auth.get_effective_group_permissions stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetEffectiveGroupPermissionsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetEffectiveGroupPermissionsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_effective_group_permissions: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([full_code, permission_title, perm_set_title, perm_set_code, perm_set_id, assignment_id]) do
    {:ok, %AuthGetEffectiveGroupPermissionsModel{
      full_code: full_code,
      permission_title: permission_title,
      perm_set_title: perm_set_title,
      perm_set_code: perm_set_code,
      perm_set_id: perm_set_id,
      assignment_id: assignment_id,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_effective_group_permissions result")
    {:error, :invalid_row}
  end
end