# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetInvitationActionsParser do
  @moduledoc """
  Parser for auth.get_invitation_actions stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetInvitationActionsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetInvitationActionsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_invitation_actions returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([invitation_action_id, action_type_code, executor_code, phase_code, condition_code, sequence, is_required, status_code, payload, result_data, error_message, completed_at, created_at]) do
    {:ok, %AuthGetInvitationActionsModel{
      invitation_action_id: invitation_action_id,
      action_type_code: action_type_code,
      executor_code: executor_code,
      phase_code: phase_code,
      condition_code: condition_code,
      sequence: sequence,
      is_required: is_required,
      status_code: status_code,
      payload: payload,
      result_data: result_data,
      error_message: error_message,
      completed_at: completed_at,
      created_at: created_at,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_invitation_actions result")
    {:error, :invalid_row}
  end
end