# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthEnsureGroupsAndPermissionsParser do
  @moduledoc """
  Parser for auth.ensure_groups_and_permissions stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthEnsureGroupsAndPermissionsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthEnsureGroupsAndPermissionsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure ensure_groups_and_permissions: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([tenant_id, tenant_uuid, groups, permissions, short_code_permissions]) do
    {:ok, %AuthEnsureGroupsAndPermissionsModel{
      tenant_id: tenant_id,
      tenant_uuid: tenant_uuid,
      groups: groups,
      permissions: permissions,
      short_code_permissions: short_code_permissions,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_groups_and_permissions result")
    {:error, :invalid_row}
  end
end