# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthAddToBlacklistParser do
  @moduledoc """
  Parser for auth.add_to_blacklist stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthAddToBlacklistModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthAddToBlacklistModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure add_to_blacklist: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([add_to_blacklist]) do
    {:ok, %AuthAddToBlacklistModel{
      add_to_blacklist: add_to_blacklist,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in add_to_blacklist result")
    {:error, :invalid_row}
  end
end