# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthRegisterUserParser do
  @moduledoc """
  Parser for auth.register_user stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthRegisterUserModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthRegisterUserModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "register_user",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_id, code, uuid, username, email, display_name]) do
    {:ok, %AuthRegisterUserModel{
      user_id: user_id,
      code: code,
      uuid: uuid,
      username: username,
      email: email,
      display_name: display_name,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in register_user result")
    {:error, :invalid_row}
  end
end