# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthAssignResourceRoleParser do
  @moduledoc """
  Parser for auth.assign_resource_role stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthAssignResourceRoleModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthAssignResourceRoleModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure assign_resource_role returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([resource_role_assignment_id, role_code]) do
    {:ok, %AuthAssignResourceRoleModel{
      resource_role_assignment_id: resource_role_assignment_id,
      role_code: role_code,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in assign_resource_role result")
    {:error, :invalid_row}
  end
end