# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetProvidersParser do
  @moduledoc """
  Parser for auth.get_providers stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetProvidersModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetProvidersModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_providers: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([provider_id, code, name, is_active, allows_group_mapping, allows_group_sync]) do
    {:ok, %AuthGetProvidersModel{
      provider_id: provider_id,
      code: code,
      name: name,
      is_active: is_active,
      allows_group_mapping: allows_group_mapping,
      allows_group_sync: allows_group_sync,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_providers result")
    {:error, :invalid_row}
  end
end