# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthSearchBlacklistParser do
  @moduledoc """
  Parser for auth.search_blacklist stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthSearchBlacklistModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthSearchBlacklistModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure search_blacklist: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([blacklist_id, username, provider_code, provider_uid, provider_oid, original_user_id, reason, notes, created_at, created_by, total_items]) do
    {:ok, %AuthSearchBlacklistModel{
      blacklist_id: blacklist_id,
      username: username,
      provider_code: provider_code,
      provider_uid: provider_uid,
      provider_oid: provider_oid,
      original_user_id: original_user_id,
      reason: reason,
      notes: notes,
      created_at: created_at,
      created_by: created_by,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_blacklist result")
    {:error, :invalid_row}
  end
end