# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthRevokeAllResourceRolesParser do
  @moduledoc """
  Parser for auth.revoke_all_resource_roles stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthRevokeAllResourceRolesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthRevokeAllResourceRolesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure revoke_all_resource_roles returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([revoke_all_resource_roles]) do
    {:ok, %AuthRevokeAllResourceRolesModel{
      revoke_all_resource_roles: revoke_all_resource_roles,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in revoke_all_resource_roles result")
    {:error, :invalid_row}
  end
end