# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthDeleteApiKeyParser do
  @moduledoc """
  Parser for auth.delete_api_key stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthDeleteApiKeyModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthDeleteApiKeyModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "delete_api_key",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([delete_api_key]) do
    {:ok, %AuthDeleteApiKeyModel{
      delete_api_key: delete_api_key,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in delete_api_key result")
    {:error, :invalid_row}
  end
end