# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthEnsureProviderParser do
  @moduledoc """
  Parser for auth.ensure_provider stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthEnsureProviderModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthEnsureProviderModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure ensure_provider returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([provider_id, is_new]) do
    {:ok, %AuthEnsureProviderModel{
      provider_id: provider_id,
      is_new: is_new,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_provider result")
    {:error, :invalid_row}
  end
end