# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthRemoveFromBlacklistParser do
  @moduledoc """
  Parser for auth.remove_from_blacklist stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthRemoveFromBlacklistModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthRemoveFromBlacklistModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure remove_from_blacklist: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([removed_blacklist_id, username, provider_code]) do
    {:ok,
     %AuthRemoveFromBlacklistModel{
       removed_blacklist_id: removed_blacklist_id,
       username: username,
       provider_code: provider_code
     }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in remove_from_blacklist result")
    {:error, :invalid_row}
  end
end
