# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthHasPermissionParser do
  @moduledoc """
  Parser for auth.has_permission stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthHasPermissionModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthHasPermissionModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure has_permission: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([has_permission]) do
    {:ok, %AuthHasPermissionModel{
      has_permission: has_permission,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in has_permission result")
    {:error, :invalid_row}
  end
end