# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthAssignPermissionParser do
  @moduledoc """
  Parser for auth.assign_permission stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthAssignPermissionModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthAssignPermissionModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure assign_permission returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, assignment_id, tenant_id, user_group_id, user_id, perm_set_id, permission_id]) do
    {:ok, %AuthAssignPermissionModel{
      created_at: created_at,
      created_by: created_by,
      assignment_id: assignment_id,
      tenant_id: tenant_id,
      user_group_id: user_group_id,
      user_id: user_id,
      perm_set_id: perm_set_id,
      permission_id: permission_id,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in assign_permission result")
    {:error, :invalid_row}
  end
end