# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthDisableUserParser do
  @moduledoc """
  Parser for auth.disable_user stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthDisableUserModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthDisableUserModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure disable_user: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_id, is_active, is_locked]) do
    {:ok, %AuthDisableUserModel{
      user_id: user_id,
      is_active: is_active,
      is_locked: is_locked,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in disable_user result")
    {:error, :invalid_row}
  end
end