# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetInvitationsParser do
  @moduledoc """
  Parser for auth.get_invitations stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetInvitationsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetInvitationsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_invitations returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([invitation_id, uuid, tenant_id, inviter_user_id, target_email, target_user_id, status_code, message, template_code, expires_at, accepted_at, rejected_at, revoked_at, created_at, created_by, action_count, pending_actions]) do
    {:ok, %AuthGetInvitationsModel{
      invitation_id: invitation_id,
      uuid: uuid,
      tenant_id: tenant_id,
      inviter_user_id: inviter_user_id,
      target_email: target_email,
      target_user_id: target_user_id,
      status_code: status_code,
      message: message,
      template_code: template_code,
      expires_at: expires_at,
      accepted_at: accepted_at,
      rejected_at: rejected_at,
      revoked_at: revoked_at,
      created_at: created_at,
      created_by: created_by,
      action_count: action_count,
      pending_actions: pending_actions,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_invitations result")
    {:error, :invalid_row}
  end
end