# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetResourceRoleAssignmentsParser do
  @moduledoc """
  Parser for auth.get_resource_role_assignments stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetResourceRoleAssignmentsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetResourceRoleAssignmentsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_resource_role_assignments returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([resource_role_assignment_id, user_id, user_display_name, user_group_id, group_title, role_code, role_title, access_flags, granted_by, granted_by_name, created_at]) do
    {:ok, %AuthGetResourceRoleAssignmentsModel{
      resource_role_assignment_id: resource_role_assignment_id,
      user_id: user_id,
      user_display_name: user_display_name,
      user_group_id: user_group_id,
      group_title: group_title,
      role_code: role_code,
      role_title: role_title,
      access_flags: access_flags,
      granted_by: granted_by,
      granted_by_name: granted_by_name,
      created_at: created_at,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_resource_role_assignments result")
    {:error, :invalid_row}
  end
end