# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthIsBlacklistedParser do
  @moduledoc """
  Parser for auth.is_blacklisted stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthIsBlacklistedModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthIsBlacklistedModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure is_blacklisted: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([is_blacklisted]) do
    {:ok, %AuthIsBlacklistedModel{
      is_blacklisted: is_blacklisted,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in is_blacklisted result")
    {:error, :invalid_row}
  end
end