# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGenerateApiKeyParser do
  @moduledoc """
  Parser for auth.generate_api_key stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGenerateApiKeyModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGenerateApiKeyModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure generate_api_key returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([generate_api_key]) do
    {:ok, %AuthGenerateApiKeyModel{
      generate_api_key: generate_api_key,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in generate_api_key result")
    {:error, :invalid_row}
  end
end