# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthEnsureUserGroupsParser do
  @moduledoc """
  Parser for auth.ensure_user_groups stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthEnsureUserGroupsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthEnsureUserGroupsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure ensure_user_groups: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, updated_at, updated_by, user_group_id, tenant_id, title, code, is_system, is_external, is_assignable, is_active, is_default, can_members_manage_others, can_members_see_others, is_synced, create_missing_users_on_sync, nrm_search_data, source]) do
    {:ok, %AuthEnsureUserGroupsModel{
      created_at: created_at,
      created_by: created_by,
      updated_at: updated_at,
      updated_by: updated_by,
      user_group_id: user_group_id,
      tenant_id: tenant_id,
      title: title,
      code: code,
      is_system: is_system,
      is_external: is_external,
      is_assignable: is_assignable,
      is_active: is_active,
      is_default: is_default,
      can_members_manage_others: can_members_manage_others,
      can_members_see_others: can_members_see_others,
      is_synced: is_synced,
      create_missing_users_on_sync: create_missing_users_on_sync,
      nrm_search_data: nrm_search_data,
      source: source,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_user_groups result")
    {:error, :invalid_row}
  end
end