# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthSearchApiKeysParser do
  @moduledoc """
  Parser for auth.search_api_keys stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthSearchApiKeysModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthSearchApiKeysModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure search_api_keys returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_by, created_at, updated_by, updated_at, api_key_id, tenant_id, title, description, api_key, expire_at, notification_email, total_items]) do
    {:ok, %AuthSearchApiKeysModel{
      created_by: created_by,
      created_at: created_at,
      updated_by: updated_by,
      updated_at: updated_at,
      api_key_id: api_key_id,
      tenant_id: tenant_id,
      title: title,
      description: description,
      api_key: api_key,
      expire_at: expire_at,
      notification_email: notification_email,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_api_keys result")
    {:error, :invalid_row}
  end
end