# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateMfaPolicyParser do
  @moduledoc """
  Parser for auth.create_mfa_policy stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateMfaPolicyModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateMfaPolicyModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_mfa_policy returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([create_mfa_policy]) do
    {:ok, %AuthCreateMfaPolicyModel{
      create_mfa_policy: create_mfa_policy,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_mfa_policy result")
    {:error, :invalid_row}
  end
end