# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserIdentityParser do
  @moduledoc """
  Parser for auth.get_user_identity stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserIdentityModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserIdentityModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_user_identity: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_identity_id, provider_code, uid, user_id, provider_groups, provider_roles, user_data, is_verified]) do
    {:ok, %AuthGetUserIdentityModel{
      user_identity_id: user_identity_id,
      provider_code: provider_code,
      uid: uid,
      user_id: user_id,
      provider_groups: provider_groups,
      provider_roles: provider_roles,
      user_data: user_data,
      is_verified: is_verified,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_identity result")
    {:error, :invalid_row}
  end
end