# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetMfaStatusParser do
  @moduledoc """
  Parser for auth.get_mfa_status stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetMfaStatusModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetMfaStatusModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_mfa_status: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_mfa_id, mfa_type_code, is_enabled, is_confirmed, enrolled_at, confirmed_at, recovery_codes_remaining]) do
    {:ok, %AuthGetMfaStatusModel{
      user_mfa_id: user_mfa_id,
      mfa_type_code: mfa_type_code,
      is_enabled: is_enabled,
      is_confirmed: is_confirmed,
      enrolled_at: enrolled_at,
      confirmed_at: confirmed_at,
      recovery_codes_remaining: recovery_codes_remaining,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_mfa_status result")
    {:error, :invalid_row}
  end
end