# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateUserEventParser do
  @moduledoc """
  Parser for auth.create_user_event stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateUserEventModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateUserEventModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_user_event returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([create_user_event]) do
    {:ok, %AuthCreateUserEventModel{
      create_user_event: create_user_event,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_user_event result")
    {:error, :invalid_row}
  end
end