# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateBlacklistUserParser do
  @moduledoc """
  Parser for auth.create_blacklist_user stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateBlacklistUserModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateBlacklistUserModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure create_blacklist_user: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([create_blacklist_user]) do
    {:ok, %AuthCreateBlacklistUserModel{
      create_blacklist_user: create_blacklist_user,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_blacklist_user result")
    {:error, :invalid_row}
  end
end