# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateInvitationTemplateParser do
  @moduledoc """
  Parser for auth.create_invitation_template stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateInvitationTemplateModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateInvitationTemplateModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_invitation_template returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([create_invitation_template]) do
    {:ok, %AuthCreateInvitationTemplateModel{
      create_invitation_template: create_invitation_template,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_invitation_template result")
    {:error, :invalid_row}
  end
end