# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetOutboundApiKeySecretByIdParser do
  @moduledoc """
  Parser for auth.get_outbound_api_key_secret_by_id stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetOutboundApiKeySecretByIdModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetOutboundApiKeySecretByIdModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_outbound_api_key_secret_by_id",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([api_key_id, service_code, service_url, encrypted_secret, extra_data]) do
    {:ok, %AuthGetOutboundApiKeySecretByIdModel{
      api_key_id: api_key_id,
      service_code: service_code,
      service_url: service_url,
      encrypted_secret: encrypted_secret,
      extra_data: extra_data,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_outbound_api_key_secret_by_id result")
    {:error, :invalid_row}
  end
end