# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthHasResourceAccessParser do
  @moduledoc """
  Parser for auth.has_resource_access stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthHasResourceAccessModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthHasResourceAccessModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure has_resource_access returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([has_resource_access]) do
    {:ok, %AuthHasResourceAccessModel{
      has_resource_access: has_resource_access,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in has_resource_access result")
    {:error, :invalid_row}
  end
end