# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthValidateApiKeyParser do
  @moduledoc """
  Parser for auth.validate_api_key stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthValidateApiKeyModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthValidateApiKeyModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure validate_api_key: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_id, username, user_display_name, permission_full_codes]) do
    {:ok, %AuthValidateApiKeyModel{
      user_id: user_id,
      username: username,
      user_display_name: user_display_name,
      permission_full_codes: permission_full_codes,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in validate_api_key result")
    {:error, :invalid_row}
  end
end