# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthEnsureResourceTypeFlagsParser do
  @moduledoc """
  Parser for auth.ensure_resource_type_flags stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthEnsureResourceTypeFlagsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthEnsureResourceTypeFlagsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure ensure_resource_type_flags returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([resource_type_code, access_flag_code]) do
    {:ok, %AuthEnsureResourceTypeFlagsModel{
      resource_type_code: resource_type_code,
      access_flag_code: access_flag_code,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in ensure_resource_type_flags result")
    {:error, :invalid_row}
  end
end