# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreatePermSetParser do
  @moduledoc """
  Parser for auth.create_perm_set stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreatePermSetModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreatePermSetModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_perm_set returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, updated_at, updated_by, perm_set_id, tenant_id, code, is_system, is_assignable, source]) do
    {:ok, %AuthCreatePermSetModel{
      created_at: created_at,
      created_by: created_by,
      updated_at: updated_at,
      updated_by: updated_by,
      perm_set_id: perm_set_id,
      tenant_id: tenant_id,
      code: code,
      is_system: is_system,
      is_assignable: is_assignable,
      source: source,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_perm_set result")
    {:error, :invalid_row}
  end
end