# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthSearchUserGroupsParser do
  @moduledoc """
  Parser for auth.search_user_groups stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthSearchUserGroupsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthSearchUserGroupsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure search_user_groups: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_group_id, title, code, is_system, is_external, is_assignable, is_active, is_default, member_count, total_items]) do
    {:ok, %AuthSearchUserGroupsModel{
      user_group_id: user_group_id,
      title: title,
      code: code,
      is_system: is_system,
      is_external: is_external,
      is_assignable: is_assignable,
      is_active: is_active,
      is_default: is_default,
      member_count: member_count,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_user_groups result")
    {:error, :invalid_row}
  end
end