# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthUnassignApiKeyPermissionsParser do
  @moduledoc """
  Parser for auth.unassign_api_key_permissions stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthUnassignApiKeyPermissionsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthUnassignApiKeyPermissionsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure unassign_api_key_permissions: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([assignment_id, perm_set_id, perm_set_code, perm_set_title, permission_full_code, permission_full_title, permission_title]) do
    {:ok, %AuthUnassignApiKeyPermissionsModel{
      assignment_id: assignment_id,
      perm_set_id: perm_set_id,
      perm_set_code: perm_set_code,
      perm_set_title: perm_set_title,
      permission_full_code: permission_full_code,
      permission_full_title: permission_full_title,
      permission_title: permission_title,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in unassign_api_key_permissions result")
    {:error, :invalid_row}
  end
end