# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthUpdateUserLastSelectedTenantParser do
  @moduledoc """
  Parser for auth.update_user_last_selected_tenant stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthUpdateUserLastSelectedTenantModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthUpdateUserLastSelectedTenantModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure update_user_last_selected_tenant: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([used_id, tenant_id]) do
    {:ok, %AuthUpdateUserLastSelectedTenantModel{
      used_id: used_id,
      tenant_id: tenant_id,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in update_user_last_selected_tenant result")
    {:error, :invalid_row}
  end
end