# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreatePermSetPermissionsParser do
  @moduledoc """
  Parser for auth.create_perm_set_permissions stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreatePermSetPermissionsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreatePermSetPermissionsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_perm_set_permissions returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([perm_set_id, perm_set_code, permission_id, permission_full_code]) do
    {:ok, %AuthCreatePermSetPermissionsModel{
      perm_set_id: perm_set_id,
      perm_set_code: perm_set_code,
      permission_id: permission_id,
      permission_full_code: permission_full_code,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_perm_set_permissions result")
    {:error, :invalid_row}
  end
end