# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateUserGroupMappingParser do
  @moduledoc """
  Parser for auth.create_user_group_mapping stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateUserGroupMappingModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateUserGroupMappingModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure create_user_group_mapping: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_group_mapping_id, user_group_id]) do
    {:ok, %AuthCreateUserGroupMappingModel{
      user_group_mapping_id: user_group_mapping_id,
      user_group_id: user_group_id,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_user_group_mapping result")
    {:error, :invalid_row}
  end
end