# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetTenantByIdParser do
  @moduledoc """
  Parser for auth.get_tenant_by_id stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetTenantByIdModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetTenantByIdModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_tenant_by_id returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, updated_at, updated_by, tenant_id, uuid, title, code, is_removable, is_assignable]) do
    {:ok, %AuthGetTenantByIdModel{
      created_at: created_at,
      created_by: created_by,
      updated_at: updated_at,
      updated_by: updated_by,
      tenant_id: tenant_id,
      uuid: uuid,
      title: title,
      code: code,
      is_removable: is_removable,
      is_assignable: is_assignable,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_tenant_by_id result")
    {:error, :invalid_row}
  end
end