# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthDeleteTenantByUuidParser do
  @moduledoc """
  Parser for auth.delete_tenant_by_uuid stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthDeleteTenantByUuidModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthDeleteTenantByUuidModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "delete_tenant_by_uuid",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([tenant_id, uuid, code]) do
    {:ok, %AuthDeleteTenantByUuidModel{
      tenant_id: tenant_id,
      uuid: uuid,
      code: code,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in delete_tenant_by_uuid result")
    {:error, :invalid_row}
  end
end