# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthProcessExternalGroupMemberSyncParser do
  @moduledoc """
  Parser for auth.process_external_group_member_sync stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthProcessExternalGroupMemberSyncModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthProcessExternalGroupMemberSyncModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure process_external_group_member_sync: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_group_id, user_group_mapping_id, state_code, user_id, upn]) do
    {:ok, %AuthProcessExternalGroupMemberSyncModel{
      user_group_id: user_group_id,
      user_group_mapping_id: user_group_mapping_id,
      state_code: state_code,
      user_id: user_id,
      upn: upn,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in process_external_group_member_sync result")
    {:error, :invalid_row}
  end
end