# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthIsOwnerParser do
  @moduledoc """
  Parser for auth.is_owner stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthIsOwnerModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthIsOwnerModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure is_owner: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([is_owner]) do
    {:ok, %AuthIsOwnerModel{
      is_owner: is_owner,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in is_owner result")
    {:error, :invalid_row}
  end
end