# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetSysParamParser do
  @moduledoc """
  Parser for auth.get_sys_param stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetSysParamModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetSysParamModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_sys_param returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, updated_at, updated_by, sys_param_id, group_code, code, text_value, number_value, bool_value]) do
    {:ok, %AuthGetSysParamModel{
      created_at: created_at,
      created_by: created_by,
      updated_at: updated_at,
      updated_by: updated_by,
      sys_param_id: sys_param_id,
      group_code: group_code,
      code: code,
      text_value: text_value,
      number_value: number_value,
      bool_value: bool_value,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_sys_param result")
    {:error, :invalid_row}
  end
end