# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetMfaPoliciesParser do
  @moduledoc """
  Parser for auth.get_mfa_policies stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetMfaPoliciesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetMfaPoliciesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_mfa_policies: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([mfa_policy_id, tenant_id, user_group_id, user_id, mfa_required, created_at, created_by]) do
    {:ok, %AuthGetMfaPoliciesModel{
      mfa_policy_id: mfa_policy_id,
      tenant_id: tenant_id,
      user_group_id: user_group_id,
      user_id: user_id,
      mfa_required: mfa_required,
      created_at: created_at,
      created_by: created_by,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_mfa_policies result")
    {:error, :invalid_row}
  end
end