# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetTenantMembersParser do
  @moduledoc """
  Parser for auth.get_tenant_members stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetTenantMembersModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetTenantMembersModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_tenant_members: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_id, user_display_name, user_code, user_uuid, user_tenant_groups]) do
    {:ok, %AuthGetTenantMembersModel{
      user_id: user_id,
      user_display_name: user_display_name,
      user_code: user_code,
      user_uuid: user_uuid,
      user_tenant_groups: user_tenant_groups,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_tenant_members result")
    {:error, :invalid_row}
  end
end