# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetAllTenantsParser do
  @moduledoc """
  Parser for auth.get_all_tenants stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetAllTenantsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetAllTenantsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_all_tenants returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([tenant_id, tenant_uuid, tenant_code, tenant_title]) do
    {:ok, %AuthGetAllTenantsModel{
      tenant_id: tenant_id,
      tenant_uuid: tenant_uuid,
      tenant_code: tenant_code,
      tenant_title: tenant_title,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_all_tenants result")
    {:error, :invalid_row}
  end
end