# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthRevokeResourceAccessParser do
  @moduledoc """
  Parser for auth.revoke_resource_access stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthRevokeResourceAccessModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthRevokeResourceAccessModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure revoke_resource_access returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([revoke_resource_access]) do
    {:ok, %AuthRevokeResourceAccessModel{
      revoke_resource_access: revoke_resource_access,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in revoke_resource_access result")
    {:error, :invalid_row}
  end
end