# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetUserIdentityByEmailParser do
  @moduledoc """
  Parser for auth.get_user_identity_by_email stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetUserIdentityByEmailModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetUserIdentityByEmailModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_user_identity_by_email",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_identity_id, provider_code, uid, user_id, provider_groups, provider_roles, user_data]) do
    {:ok, %AuthGetUserIdentityByEmailModel{
      user_identity_id: user_identity_id,
      provider_code: provider_code,
      uid: uid,
      user_id: user_id,
      provider_groups: provider_groups,
      provider_roles: provider_roles,
      user_data: user_data,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_user_identity_by_email result")
    {:error, :invalid_row}
  end
end