# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateTokenParser do
  @moduledoc """
  Parser for auth.create_token stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateTokenModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateTokenModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure create_token: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([token_id, token_uid, expires_at]) do
    {:ok, %AuthCreateTokenModel{
      token_id: token_id,
      token_uid: token_uid,
      expires_at: expires_at,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_token result")
    {:error, :invalid_row}
  end
end