# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthSearchUserGroupMappingsParser do
  @moduledoc """
  Parser for auth.search_user_group_mappings stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthSearchUserGroupMappingsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthSearchUserGroupMappingsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure search_user_group_mappings: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_group_mapping_id, user_group_id, user_group_title, user_group_code, provider_code, mapped_object_id, mapped_object_name, mapped_role, total_items]) do
    {:ok, %AuthSearchUserGroupMappingsModel{
      user_group_mapping_id: user_group_mapping_id,
      user_group_id: user_group_id,
      user_group_title: user_group_title,
      user_group_code: user_group_code,
      provider_code: provider_code,
      mapped_object_id: mapped_object_id,
      mapped_object_name: mapped_object_name,
      mapped_role: mapped_role,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_user_group_mappings result")
    {:error, :invalid_row}
  end
end