# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthUpdateUserPreferencesParser do
  @moduledoc """
  Parser for auth.update_user_preferences stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthUpdateUserPreferencesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthUpdateUserPreferencesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure update_user_preferences: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([updated_at, updated_by]) do
    {:ok, %AuthUpdateUserPreferencesModel{
      updated_at: updated_at,
      updated_by: updated_by,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in update_user_preferences result")
    {:error, :invalid_row}
  end
end