# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthSearchPermissionsParser do
  @moduledoc """
  Parser for auth.search_permissions stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthSearchPermissionsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthSearchPermissionsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure search_permissions: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([permission_id, title, code, full_code, short_code, is_assignable, has_children, source, total_items]) do
    {:ok, %AuthSearchPermissionsModel{
      permission_id: permission_id,
      title: title,
      code: code,
      full_code: full_code,
      short_code: short_code,
      is_assignable: is_assignable,
      has_children: has_children,
      source: source,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_permissions result")
    {:error, :invalid_row}
  end
end