# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreateResourceTypeParser do
  @moduledoc """
  Parser for auth.create_resource_type stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreateResourceTypeModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreateResourceTypeModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_resource_type returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, title, full_title, description, is_active, source, path, key_schema, access_flags]) do
    {:ok, %AuthCreateResourceTypeModel{
      code: code,
      title: title,
      full_title: full_title,
      description: description,
      is_active: is_active,
      source: source,
      path: path,
      key_schema: key_schema,
      access_flags: access_flags,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_resource_type result")
    {:error, :invalid_row}
  end
end