# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthCreatePermissionParser do
  @moduledoc """
  Parser for auth.create_permission stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthCreatePermissionModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthCreatePermissionModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure create_permission: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, updated_at, updated_by, permission_id, is_assignable, title, code, full_code, node_path, has_children, full_title, nrm_search_data, short_code, source]) do
    {:ok, %AuthCreatePermissionModel{
      created_at: created_at,
      created_by: created_by,
      updated_at: updated_at,
      updated_by: updated_by,
      permission_id: permission_id,
      is_assignable: is_assignable,
      title: title,
      code: code,
      full_code: full_code,
      node_path: node_path,
      has_children: has_children,
      full_title: full_title,
      nrm_search_data: nrm_search_data,
      short_code: short_code,
      source: source,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_permission result")
    {:error, :invalid_row}
  end
end