# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthDisableUserIdentityParser do
  @moduledoc """
  Parser for auth.disable_user_identity stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthDisableUserIdentityModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthDisableUserIdentityModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure disable_user_identity: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_identity_id, is_active]) do
    {:ok, %AuthDisableUserIdentityModel{
      user_identity_id: user_identity_id,
      is_active: is_active,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in disable_user_identity result")
    {:error, :invalid_row}
  end
end