# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetApiKeyPermissionsParser do
  @moduledoc """
  Parser for auth.get_api_key_permissions stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetApiKeyPermissionsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetApiKeyPermissionsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_api_key_permissions: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([assignment_id, perm_set_code, perm_set_title, user_group_member_id, user_group_title, permission_inheritance_type, permission_code, permission_title]) do
    {:ok, %AuthGetApiKeyPermissionsModel{
      assignment_id: assignment_id,
      perm_set_code: perm_set_code,
      perm_set_title: perm_set_title,
      user_group_member_id: user_group_member_id,
      user_group_title: user_group_title,
      permission_inheritance_type: permission_inheritance_type,
      permission_code: permission_code,
      permission_title: permission_title,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_api_key_permissions result")
    {:error, :invalid_row}
  end
end