# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthRevokeResourceRoleParser do
  @moduledoc """
  Parser for auth.revoke_resource_role stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthRevokeResourceRoleModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthRevokeResourceRoleModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure revoke_resource_role returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([revoke_resource_role]) do
    {:ok, %AuthRevokeResourceRoleModel{
      revoke_resource_role: revoke_resource_role,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in revoke_resource_role result")
    {:error, :invalid_row}
  end
end