# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthGetResourceAccessMatrixParser do
  @moduledoc """
  Parser for auth.get_resource_access_matrix stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthGetResourceAccessMatrixModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthGetResourceAccessMatrixModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_resource_access_matrix returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([resource_type, access_flag, source]) do
    {:ok, %AuthGetResourceAccessMatrixModel{
      resource_type: resource_type,
      access_flag: access_flag,
      source: source,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_resource_access_matrix result")
    {:error, :invalid_row}
  end
end