# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthUpdateResourceTypeParser do
  @moduledoc """
  Parser for auth.update_resource_type stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthUpdateResourceTypeModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthUpdateResourceTypeModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure update_resource_type: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, title, full_title, description, is_active, source, parent_code, path, key_schema]) do
    {:ok, %AuthUpdateResourceTypeModel{
      code: code,
      title: title,
      full_title: full_title,
      description: description,
      is_active: is_active,
      source: source,
      parent_code: parent_code,
      path: path,
      key_schema: key_schema,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in update_resource_type result")
    {:error, :invalid_row}
  end
end