# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthUpdatePermissionDataV18Parser do
  @moduledoc """
  Parser for auth.update_permission_data_v1_8 stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthUpdatePermissionDataV18model

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthUpdatePermissionDataV18model.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "update_permission_data_v1_8",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([update_permission_data_v18]) do
    {:ok,
     %AuthUpdatePermissionDataV18model{
       update_permission_data_v18: update_permission_data_v18
     }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in update_permission_data_v1_8 result")
    {:error, :invalid_row}
  end
end
