# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.AuthResetMfaParser do
  @moduledoc """
  Parser for auth.reset_mfa stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.AuthResetMfaModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [AuthResetMfaModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure reset_mfa returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([user_mfa_id, recovery_codes]) do
    {:ok, %AuthResetMfaModel{
      user_mfa_id: user_mfa_id,
      recovery_codes: recovery_codes,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in reset_mfa result")
    {:error, :invalid_row}
  end
end