# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.CopyTranslationsParser do
  @moduledoc """
  Parser for public.copy_translations stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.CopyTranslationsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [CopyTranslationsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure copy_translations: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([operation, count]) do
    {:ok, %CopyTranslationsModel{
      operation: operation,
      count: count,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in copy_translations result")
    {:error, :invalid_row}
  end
end