# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.CreateTranslationParser do
  @moduledoc """
  Parser for public.create_translation stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.CreateTranslationModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [CreateTranslationModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_translation returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, updated_at, updated_by, translation_id, language_code, tenant_id, data_group, data_object_code, data_object_id, context, value, nrm_search_data, ts_search_data]) do
    {:ok, %CreateTranslationModel{
      created_at: created_at,
      created_by: created_by,
      updated_at: updated_at,
      updated_by: updated_by,
      translation_id: translation_id,
      language_code: language_code,
      tenant_id: tenant_id,
      data_group: data_group,
      data_object_code: data_object_code,
      data_object_id: data_object_id,
      context: context,
      value: value,
      nrm_search_data: nrm_search_data,
      ts_search_data: ts_search_data,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_translation result")
    {:error, :invalid_row}
  end
end