# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.CreateEventCategoryParser do
  @moduledoc """
  Parser for public.create_event_category stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.CreateEventCategoryModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [CreateEventCategoryModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure create_event_category: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([category_code, range_start, range_end, is_error, source]) do
    {:ok, %CreateEventCategoryModel{
      category_code: category_code,
      range_start: range_start,
      range_end: range_end,
      is_error: is_error,
      source: source,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_event_category result")
    {:error, :invalid_row}
  end
end