# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.CreateEventCodeParser do
  @moduledoc """
  Parser for public.create_event_code stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.CreateEventCodeModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [CreateEventCodeModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "create_event_code",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([event_id, code, category_code, title, description, is_read_only, is_system]) do
    {:ok, %CreateEventCodeModel{
      event_id: event_id,
      code: code,
      category_code: category_code,
      title: title,
      description: description,
      is_read_only: is_read_only,
      is_system: is_system,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_event_code result")
    {:error, :invalid_row}
  end
end