# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.CreateEventMessageParser do
  @moduledoc """
  Parser for public.create_event_message stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.CreateEventMessageModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [CreateEventMessageModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure create_event_message: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, updated_at, updated_by, event_message_id, event_id, language_code, message_template, is_active]) do
    {:ok, %CreateEventMessageModel{
      created_at: created_at,
      created_by: created_by,
      updated_at: updated_at,
      updated_by: updated_by,
      event_message_id: event_message_id,
      event_id: event_id,
      language_code: language_code,
      message_template: message_template,
      is_active: is_active,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_event_message result")
    {:error, :invalid_row}
  end
end