# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.CreateJournalMessageByCodeParser do
  @moduledoc """
  Parser for public.create_journal_message_by_code stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.CreateJournalMessageByCodeModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [CreateJournalMessageByCodeModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "create_journal_message_by_code",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, correlation_id, journal_id, tenant_id, event_id, user_id, keys, data_payload]) do
    {:ok, %CreateJournalMessageByCodeModel{
      created_at: created_at,
      created_by: created_by,
      correlation_id: correlation_id,
      journal_id: journal_id,
      tenant_id: tenant_id,
      event_id: event_id,
      user_id: user_id,
      keys: keys,
      data_payload: data_payload,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_journal_message_by_code result")
    {:error, :invalid_row}
  end
end