# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.CreateLanguageParser do
  @moduledoc """
  Parser for public.create_language stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.CreateLanguageModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [CreateLanguageModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure create_language returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created_at, created_by, updated_at, updated_by, code, value, tenant_id, is_frontend_language, is_backend_language, is_communication_language, frontend_logical_order, backend_logical_order, communication_logical_order, is_default_frontend, is_default_backend, is_default_communication, custom_data]) do
    {:ok, %CreateLanguageModel{
      created_at: created_at,
      created_by: created_by,
      updated_at: updated_at,
      updated_by: updated_by,
      code: code,
      value: value,
      tenant_id: tenant_id,
      is_frontend_language: is_frontend_language,
      is_backend_language: is_backend_language,
      is_communication_language: is_communication_language,
      frontend_logical_order: frontend_logical_order,
      backend_logical_order: backend_logical_order,
      communication_logical_order: communication_logical_order,
      is_default_frontend: is_default_frontend,
      is_default_backend: is_default_backend,
      is_default_communication: is_default_communication,
      custom_data: custom_data,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in create_language result")
    {:error, :invalid_row}
  end
end