# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.FormatJournalMessageParser do
  @moduledoc """
  Parser for public.format_journal_message stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.FormatJournalMessageModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [FormatJournalMessageModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure format_journal_message: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([format_journal_message]) do
    {:ok, %FormatJournalMessageModel{
      format_journal_message: format_journal_message,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in format_journal_message result")
    {:error, :invalid_row}
  end
end