# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.GetJournalPayloadParser do
  @moduledoc """
  Parser for public.get_journal_payload stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.GetJournalPayloadModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetJournalPayloadModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_journal_payload",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([journal_id, payload]) do
    {:ok, %GetJournalPayloadModel{
      journal_id: journal_id,
      payload: payload,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_journal_payload result")
    {:error, :invalid_row}
  end
end