# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.GetBackendLanguagesParser do
  @moduledoc """
  Parser for public.get_backend_languages stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.GetBackendLanguagesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetBackendLanguagesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_backend_languages",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, value, display_name, backend_logical_order, is_default_backend, custom_data]) do
    {:ok, %GetBackendLanguagesModel{
      code: code,
      value: value,
      display_name: display_name,
      backend_logical_order: backend_logical_order,
      is_default_backend: is_default_backend,
      custom_data: custom_data,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_backend_languages result")
    {:error, :invalid_row}
  end
end