# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.GetLanguagesParser do
  @moduledoc """
  Parser for public.get_languages stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.GetLanguagesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetLanguagesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_languages",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, value, display_name, is_frontend_language, is_backend_language, is_communication_language, frontend_logical_order, backend_logical_order, communication_logical_order, is_default_frontend, is_default_backend, is_default_communication, custom_data]) do
    {:ok, %GetLanguagesModel{
      code: code,
      value: value,
      display_name: display_name,
      is_frontend_language: is_frontend_language,
      is_backend_language: is_backend_language,
      is_communication_language: is_communication_language,
      frontend_logical_order: frontend_logical_order,
      backend_logical_order: backend_logical_order,
      communication_logical_order: communication_logical_order,
      is_default_frontend: is_default_frontend,
      is_default_backend: is_default_backend,
      is_default_communication: is_default_communication,
      custom_data: custom_data,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_languages result")
    {:error, :invalid_row}
  end
end