# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.GetJournalEntryParser do
  @moduledoc """
  Parser for public.get_journal_entry stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.GetJournalEntryModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetJournalEntryModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_journal_entry returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([journal_id, event_id, event_code, event_category, message, keys, payload, request_context, created_at, created_by, correlation_id]) do
    {:ok, %GetJournalEntryModel{
      journal_id: journal_id,
      event_id: event_id,
      event_code: event_code,
      event_category: event_category,
      message: message,
      keys: keys,
      payload: payload,
      request_context: request_context,
      created_at: created_at,
      created_by: created_by,
      correlation_id: correlation_id,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_journal_entry result")
    {:error, :invalid_row}
  end
end