# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.GetVersionParser do
  @moduledoc """
  Parser for public.get_version stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.GetVersionModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetVersionModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_version returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([version_id, version, title, execution_started, execution_finished]) do
    {:ok, %GetVersionModel{
      version_id: version_id,
      version: version,
      title: title,
      execution_started: execution_started,
      execution_finished: execution_finished,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_version result")
    {:error, :invalid_row}
  end
end