# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.GetEventMessageTemplateParser do
  @moduledoc """
  Parser for public.get_event_message_template stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.GetEventMessageTemplateModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetEventMessageTemplateModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_event_message_template returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([get_event_message_template]) do
    {:ok, %GetEventMessageTemplateModel{
      get_event_message_template: get_event_message_template,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_event_message_template result")
    {:error, :invalid_row}
  end
end