# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.GetFrontendLanguagesParser do
  @moduledoc """
  Parser for public.get_frontend_languages stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.GetFrontendLanguagesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetFrontendLanguagesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_frontend_languages: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, value, display_name, frontend_logical_order, is_default_frontend, custom_data]) do
    {:ok, %GetFrontendLanguagesModel{
      code: code,
      value: value,
      display_name: display_name,
      frontend_logical_order: frontend_logical_order,
      is_default_frontend: is_default_frontend,
      custom_data: custom_data,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_frontend_languages result")
    {:error, :invalid_row}
  end
end