# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.GetGroupTranslationsParser do
  @moduledoc """
  Parser for public.get_group_translations stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.GetGroupTranslationsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetGroupTranslationsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure get_group_translations: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([get_group_translations]) do
    {:ok, %GetGroupTranslationsModel{
      get_group_translations: get_group_translations,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_group_translations result")
    {:error, :invalid_row}
  end
end