# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.GetTokenTypesParser do
  @moduledoc """
  Parser for public.get_token_types stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.GetTokenTypesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetTokenTypesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_token_types",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, default_expiration_in_seconds, is_system]) do
    {:ok, %GetTokenTypesModel{
      code: code,
      default_expiration_in_seconds: default_expiration_in_seconds,
      is_system: is_system,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_token_types result")
    {:error, :invalid_row}
  end
end