# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.GetPermissionsMapParser do
  @moduledoc """
  Parser for public.get_permissions_map stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.GetPermissionsMapModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetPermissionsMapModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "get_permissions_map",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([permission_id, full_code, short_code, title]) do
    {:ok, %GetPermissionsMapModel{
      permission_id: permission_id,
      full_code: full_code,
      short_code: short_code,
      title: title,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_permissions_map result")
    {:error, :invalid_row}
  end
end