# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.GetCommunicationLanguagesParser do
  @moduledoc """
  Parser for public.get_communication_languages stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.GetCommunicationLanguagesModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [GetCommunicationLanguagesModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure get_communication_languages returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([code, value, display_name, communication_logical_order, is_default_communication, custom_data]) do
    {:ok, %GetCommunicationLanguagesModel{
      code: code,
      value: value,
      display_name: display_name,
      communication_logical_order: communication_logical_order,
      is_default_communication: is_default_communication,
      custom_data: custom_data,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in get_communication_languages result")
    {:error, :invalid_row}
  end
end