# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.InternalResolveTenantParser do
  @moduledoc """
  Parser for internal.resolve_tenant stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.InternalResolveTenantModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [InternalResolveTenantModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure resolve_tenant: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([resolve_tenant]) do
    {:ok, %InternalResolveTenantModel{
      resolve_tenant: resolve_tenant,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in resolve_tenant result")
    {:error, :invalid_row}
  end
end