# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.InternalResolveUserParser do
  @moduledoc """
  Parser for internal.resolve_user stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.InternalResolveUserModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [InternalResolveUserModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure resolve_user: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([resolve_user]) do
    {:ok, %InternalResolveUserModel{
      resolve_user: resolve_user,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in resolve_user result")
    {:error, :invalid_row}
  end
end