# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.InternalResolveGroupParser do
  @moduledoc """
  Parser for internal.resolve_group stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.InternalResolveGroupModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [InternalResolveGroupModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure resolve_group: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([resolve_group]) do
    {:ok, %InternalResolveGroupModel{
      resolve_group: resolve_group,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in resolve_group result")
    {:error, :invalid_row}
  end
end