# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.JournalKeysParser do
  @moduledoc """
  Parser for public.journal_keys stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.JournalKeysModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [JournalKeysModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure journal_keys returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([journal_keys]) do
    {:ok, %JournalKeysModel{
      journal_keys: journal_keys,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in journal_keys result")
    {:error, :invalid_row}
  end
end