# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.PurgeAuditDataParser do
  @moduledoc """
  Parser for public.purge_audit_data stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.PurgeAuditDataModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [PurgeAuditDataModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure purge_audit_data: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([journal_deleted, user_events_deleted]) do
    {:ok, %PurgeAuditDataModel{
      journal_deleted: journal_deleted,
      user_events_deleted: user_events_deleted,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in purge_audit_data result")
    {:error, :invalid_row}
  end
end