# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.SearchJournalParser do
  @moduledoc """
  Parser for public.search_journal stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.SearchJournalModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [SearchJournalModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure search_journal returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([journal_id, event_id, event_code, event_category, user_id, message, keys, request_context, created_at, created_by, correlation_id, total_items]) do
    {:ok, %SearchJournalModel{
      journal_id: journal_id,
      event_id: event_id,
      event_code: event_code,
      event_category: event_category,
      user_id: user_id,
      message: message,
      keys: keys,
      request_context: request_context,
      created_at: created_at,
      created_by: created_by,
      correlation_id: correlation_id,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_journal result")
    {:error, :invalid_row}
  end
end