# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.SearchTranslationsParser do
  @moduledoc """
  Parser for public.search_translations stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.SearchTranslationsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [SearchTranslationsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure",
      procedure: "search_translations",
      reason: inspect(reason)
    )

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([translation_id, language_code, language_value, data_group, data_object_code, data_object_id, value, created_at, created_by, updated_at, updated_by, total_items]) do
    {:ok, %SearchTranslationsModel{
      translation_id: translation_id,
      language_code: language_code,
      language_value: language_value,
      data_group: data_group,
      data_object_code: data_object_code,
      data_object_id: data_object_id,
      value: value,
      created_at: created_at,
      created_by: created_by,
      updated_at: updated_at,
      updated_by: updated_by,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_translations result")
    {:error, :invalid_row}
  end
end