# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.SearchJournalMsgsParser do
  @moduledoc """
  Parser for public.search_journal_msgs stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.SearchJournalMsgsModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [SearchJournalMsgsModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.debug("Stored procedure search_journal_msgs returned error: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([created, created_by, journal_id, event_id, data_group, data_object_id, data_object_code, user_id, msg, total_items]) do
    {:ok, %SearchJournalMsgsModel{
      created: created,
      created_by: created_by,
      journal_id: journal_id,
      event_id: event_id,
      data_group: data_group,
      data_object_id: data_object_id,
      data_object_code: data_object_code,
      user_id: user_id,
      msg: msg,
      total_items: total_items,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in search_journal_msgs result")
    {:error, :invalid_row}
  end
end