# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Parsers.ValidateTokenParser do
  @moduledoc """
  Parser for public.validate_token stored procedure results.
  """

  require Logger

  alias KeenAuthPermissions.Database.Models.ValidateTokenModel

  @spec parse_result({:ok, Postgrex.Result.t()} | {:error, any()}) ::
          {:ok, [ValidateTokenModel.t()]} | {:error, any()}
  def parse_result({:error, reason} = err) do
    Logger.error("Error calling stored procedure validate_token: #{inspect(reason)}")

    err
  end

  def parse_result({:ok, %Postgrex.Result{rows: rows}}) do
    results =
      rows
      |> Enum.map(&parse_row/1)
      |> Enum.filter(&match?({:ok, _}, &1))
      |> Enum.map(&elem(&1, 1))

    {:ok, results}
  end

  defp parse_row([token_id, token_uid, token_state_code, used_at, user_id, user_oid, token_data]) do
    {:ok, %ValidateTokenModel{
      token_id: token_id,
      token_uid: token_uid,
      token_state_code: token_state_code,
      used_at: used_at,
      user_id: user_id,
      user_oid: user_oid,
      token_data: token_data,
    }}
  end

  defp parse_row(_row) do
    Logger.warning("Invalid row structure in validate_token result")
    {:error, :invalid_row}
  end
end