# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateBlacklistUserModel do
  @moduledoc """
  Model for auth.create_blacklist_user stored procedure result.
  """

  @type t() :: %__MODULE__{
    create_blacklist_user: integer()
  }

  @fields [:create_blacklist_user]

  @enforce_keys @fields
  defstruct @fields
end