# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateUserGroupMappingModel do
  @moduledoc """
  Model for auth.create_user_group_mapping stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_group_mapping_id: integer(),
    user_group_id: integer()
  }

  @fields [:user_group_mapping_id, :user_group_id]

  @enforce_keys @fields
  defstruct @fields
end