# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateResourceTypeModel do
  @moduledoc """
  Model for auth.create_resource_type stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    title: String.t(),
    full_title: String.t(),
    description: String.t(),
    is_active: boolean(),
    source: String.t(),
    path: String.t(),
    key_schema: map() | list(),
    access_flags: list(String.t())
  }

  @fields [:code, :title, :full_title, :description, :is_active, :source, :path, :key_schema, :access_flags]

  @enforce_keys @fields
  defstruct @fields
end