# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnsureProviderModel do
  @moduledoc """
  Model for auth.ensure_provider stored procedure result.
  """

  @type t() :: %__MODULE__{
    provider_id: integer(),
    is_new: boolean()
  }

  @fields [:provider_id, :is_new]

  @enforce_keys @fields
  defstruct @fields
end