# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetResourceGrantsModel do
  @moduledoc """
  Model for auth.get_resource_grants stored procedure result.
  """

  @type t() :: %__MODULE__{
    resource_access_id: integer(),
    user_id: integer(),
    user_display_name: String.t(),
    user_group_id: integer(),
    group_title: String.t(),
    access_flag: String.t(),
    is_deny: boolean(),
    granted_by: integer(),
    granted_by_name: String.t(),
    created_at: DateTime.t()
  }

  @fields [:resource_access_id, :user_id, :user_display_name, :user_group_id, :group_title, :access_flag, :is_deny, :granted_by, :granted_by_name, :created_at]

  @enforce_keys @fields
  defstruct @fields
end