# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthSearchApiKeysModel do
  @moduledoc """
  Model for auth.search_api_keys stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_by: String.t(),
    created_at: DateTime.t(),
    updated_by: String.t(),
    updated_at: DateTime.t(),
    api_key_id: integer(),
    tenant_id: integer(),
    title: String.t(),
    description: String.t(),
    api_key: String.t(),
    expire_at: DateTime.t(),
    notification_email: String.t(),
    total_items: integer()
  }

  @fields [:created_by, :created_at, :updated_by, :updated_at, :api_key_id, :tenant_id, :title, :description, :api_key, :expire_at, :notification_email, :total_items]

  @enforce_keys @fields
  defstruct @fields
end