# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthSearchUserGroupMappingsModel do
  @moduledoc """
  Model for auth.search_user_group_mappings stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_group_mapping_id: integer(),
    user_group_id: integer(),
    user_group_title: String.t(),
    user_group_code: String.t(),
    provider_code: String.t(),
    mapped_object_id: String.t(),
    mapped_object_name: String.t(),
    mapped_role: String.t(),
    total_items: integer()
  }

  @fields [:user_group_mapping_id, :user_group_id, :user_group_title, :user_group_code, :provider_code, :mapped_object_id, :mapped_object_name, :mapped_role, :total_items]

  @enforce_keys @fields
  defstruct @fields
end