# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdatePermissionDataV18model do
  @moduledoc """
  Model for auth.update_permission_data_v1_8 stored procedure result.
  """

  @type t() :: %__MODULE__{
          update_permission_data_v18: integer()
        }

  @fields [:update_permission_data_v18]

  @enforce_keys @fields
  defstruct @fields
end
