# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserAssignedGroupsModel do
  @moduledoc """
  Model for auth.get_user_assigned_groups stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_group_member_id: integer(),
    user_group_id: integer(),
    user_group_code: String.t(),
    user_group_title: String.t(),
    user_group_member_type_code: String.t(),
    user_group_mapping_id: integer()
  }

  @fields [:user_group_member_id, :user_group_id, :user_group_code, :user_group_title, :user_group_member_type_code, :user_group_mapping_id]

  @enforce_keys @fields
  defstruct @fields
end