# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateServiceUserInfoModel do
  @moduledoc """
  Model for auth.create_service_user_info stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_id: integer(),
    username: String.t(),
    email: String.t(),
    display_name: String.t()
  }

  @fields [:user_id, :username, :email, :display_name]

  @enforce_keys @fields
  defstruct @fields
end