# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnsureInvitationTemplatesModel do
  @moduledoc """
  Model for auth.ensure_invitation_templates stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    template_id: integer(),
    tenant_id: integer(),
    code: String.t(),
    title: String.t(),
    description: String.t(),
    is_active: boolean(),
    default_message: String.t(),
    source: String.t()
  }

  @fields [:created_at, :created_by, :updated_at, :updated_by, :template_id, :tenant_id, :code, :title, :description, :is_active, :default_message, :source]

  @enforce_keys @fields
  defstruct @fields
end