# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetInvitationActionsModel do
  @moduledoc """
  Model for auth.get_invitation_actions stored procedure result.
  """

  @type t() :: %__MODULE__{
    invitation_action_id: integer(),
    action_type_code: String.t(),
    executor_code: String.t(),
    phase_code: String.t(),
    condition_code: String.t(),
    sequence: integer(),
    is_required: boolean(),
    status_code: String.t(),
    payload: map() | list(),
    result_data: map() | list(),
    error_message: String.t(),
    completed_at: DateTime.t(),
    created_at: DateTime.t()
  }

  @fields [:invitation_action_id, :action_type_code, :executor_code, :phase_code, :condition_code, :sequence, :is_required, :status_code, :payload, :result_data, :error_message, :completed_at, :created_at]

  @enforce_keys @fields
  defstruct @fields
end