# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthAddToBlacklistModel do
  @moduledoc """
  Model for auth.add_to_blacklist stored procedure result.
  """

  @type t() :: %__MODULE__{
          add_to_blacklist: integer()
        }

  @fields [:add_to_blacklist]

  @enforce_keys @fields
  defstruct @fields
end
