# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGenerateApiKeyModel do
  @moduledoc """
  Model for auth.generate_api_key stored procedure result.
  """

  @type t() :: %__MODULE__{
    generate_api_key: String.t()
  }

  @fields [:generate_api_key]

  @enforce_keys @fields
  defstruct @fields
end