# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdatePermissionDataV19model do
  @moduledoc """
  Model for auth.update_permission_data_v1_9 stored procedure result.
  """

  @type t() :: %__MODULE__{
          update_permission_data_v19: integer()
        }

  @fields [:update_permission_data_v19]

  @enforce_keys @fields
  defstruct @fields
end
