# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetAllPermissionsModel do
  @moduledoc """
  Model for auth.get_all_permissions stored procedure result.
  """

  @type t() :: %__MODULE__{
    permission_id: integer(),
    is_assignable: boolean(),
    title: String.t(),
    code: String.t(),
    full_code: String.t(),
    has_children: boolean(),
    short_code: String.t(),
    source: String.t()
  }

  @fields [:permission_id, :is_assignable, :title, :code, :full_code, :has_children, :short_code, :source]

  @enforce_keys @fields
  defstruct @fields
end