# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthSearchPermSetsModel do
  @moduledoc """
  Model for auth.search_perm_sets stored procedure result.
  """

  @type t() :: %__MODULE__{
    perm_set_id: integer(),
    title: String.t(),
    code: String.t(),
    is_system: boolean(),
    is_assignable: boolean(),
    permission_count: integer(),
    total_items: integer()
  }

  @fields [:perm_set_id, :title, :code, :is_system, :is_assignable, :permission_count, :total_items]

  @enforce_keys @fields
  defstruct @fields
end