# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetSecurityEventsModel do
  @moduledoc """
  Model for auth.get_security_events stored procedure result.
  """

  @type t() :: %__MODULE__{
    source: String.t(),
    event_type_code: String.t(),
    requester_user_id: integer(),
    requester_username: String.t(),
    target_user_id: integer(),
    target_username: String.t(),
    request_context: map() | list(),
    event_data: map() | list(),
    correlation_id: String.t(),
    created_at: DateTime.t(),
    total_items: integer()
  }

  @fields [:source, :event_type_code, :requester_user_id, :requester_username, :target_user_id, :target_username, :request_context, :event_data, :correlation_id, :created_at, :total_items]

  @enforce_keys @fields
  defstruct @fields
end