# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateApiKeyModel do
  @moduledoc """
  Model for auth.create_api_key stored procedure result.
  """

  @type t() :: %__MODULE__{
    api_key_id: integer(),
    api_key: String.t(),
    api_secret: String.t()
  }

  @fields [:api_key_id, :api_key, :api_secret]

  @enforce_keys @fields
  defstruct @fields
end