# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthAcceptInvitationModel do
  @moduledoc """
  Model for auth.accept_invitation stored procedure result.
  """

  @type t() :: %__MODULE__{
    invitation_action_id: integer(),
    action_type_code: String.t(),
    executor_code: String.t(),
    sequence: integer(),
    payload: map() | list()
  }

  @fields [:invitation_action_id, :action_type_code, :executor_code, :sequence, :payload]

  @enforce_keys @fields
  defstruct @fields
end