# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetEffectiveGroupPermissionsModel do
  @moduledoc """
  Model for auth.get_effective_group_permissions stored procedure result.
  """

  @type t() :: %__MODULE__{
    full_code: String.t(),
    permission_title: String.t(),
    perm_set_title: String.t(),
    perm_set_code: String.t(),
    perm_set_id: integer(),
    assignment_id: integer()
  }

  @fields [:full_code, :permission_title, :perm_set_title, :perm_set_code, :perm_set_id, :assignment_id]

  @enforce_keys @fields
  defstruct @fields
end