# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdatePermissionDataV14model do
  @moduledoc """
  Model for auth.update_permission_data_v1_4 stored procedure result.
  """

  @type t() :: %__MODULE__{
          update_permission_data_v14: integer()
        }

  @fields [:update_permission_data_v14]

  @enforce_keys @fields
  defstruct @fields
end
