# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthSearchBlacklistModel do
  @moduledoc """
  Model for auth.search_blacklist stored procedure result.
  """

  @type t() :: %__MODULE__{
    blacklist_id: integer(),
    username: String.t(),
    provider_code: String.t(),
    provider_uid: String.t(),
    provider_oid: String.t(),
    original_user_id: integer(),
    reason: String.t(),
    notes: String.t(),
    created_at: DateTime.t(),
    created_by: String.t(),
    total_items: integer()
  }

  @fields [:blacklist_id, :username, :provider_code, :provider_uid, :provider_oid, :original_user_id, :reason, :notes, :created_at, :created_by, :total_items]

  @enforce_keys @fields
  defstruct @fields
end