# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthDeleteResourceRoleModel do
  @moduledoc """
  Model for auth.delete_resource_role stored procedure result.
  """

  @type t() :: %__MODULE__{
    delete_resource_role: integer()
  }

  @fields [:delete_resource_role]

  @enforce_keys @fields
  defstruct @fields
end