# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateUserGroupMemberModel do
  @moduledoc """
  Model for auth.create_user_group_member stored procedure result.
  """

  @type t() :: %__MODULE__{
    create_user_group_member: integer()
  }

  @fields [:create_user_group_member]

  @enforce_keys @fields
  defstruct @fields
end