# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnsureUserGroupMappingModel do
  @moduledoc """
  Model for auth.ensure_user_group_mapping stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_group_mapping_id: integer(),
    user_group_id: integer(),
    is_new: boolean()
  }

  @fields [:user_group_mapping_id, :user_group_id, :is_new]

  @enforce_keys @fields
  defstruct @fields
end