# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthHasPermissionsModel do
  @moduledoc """
  Model for auth.has_permissions stored procedure result.
  """

  @type t() :: %__MODULE__{
    has_permissions: boolean()
  }

  @fields [:has_permissions]

  @enforce_keys @fields
  defstruct @fields
end