# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetTenantGroupsModel do
  @moduledoc """
  Model for auth.get_tenant_groups stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_group_id: integer(),
    group_code: String.t(),
    group_title: String.t(),
    is_external: boolean(),
    is_assignable: boolean(),
    is_active: boolean(),
    members_count: integer()
  }

  @fields [:user_group_id, :group_code, :group_title, :is_external, :is_assignable, :is_active, :members_count]

  @enforce_keys @fields
  defstruct @fields
end