# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthHasPermissionModel do
  @moduledoc """
  Model for auth.has_permission stored procedure result.
  """

  @type t() :: %__MODULE__{
    has_permission: boolean()
  }

  @fields [:has_permission]

  @enforce_keys @fields
  defstruct @fields
end