# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserPreferencesModel do
  @moduledoc """
  Model for auth.get_user_preferences stored procedure result.
  """

  @type t() :: %__MODULE__{
    get_user_preferences: String.t()
  }

  @fields [:get_user_preferences]

  @enforce_keys @fields
  defstruct @fields
end