# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreatePermSetModel do
  @moduledoc """
  Model for auth.create_perm_set stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    perm_set_id: integer(),
    tenant_id: integer() | nil,
    code: String.t(),
    is_system: boolean(),
    is_assignable: boolean(),
    nrm_search_data: String.t() | nil,
    source: String.t() | nil
  }

  @fields [:created_at, :created_by, :updated_at, :updated_by, :perm_set_id, :tenant_id, :code, :is_system, :is_assignable, :nrm_search_data, :source]

  @enforce_keys @fields
  defstruct @fields
end