# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserAccessibleResourcesModel do
  @moduledoc """
  Model for auth.get_user_accessible_resources stored procedure result.
  """

  @type t() :: %__MODULE__{
    resource_id: map() | list(),
    resource_path: String.t(),
    access_flags: list(String.t()),
    source: String.t()
  }

  @fields [:resource_id, :resource_path, :access_flags, :source]

  @enforce_keys @fields
  defstruct @fields
end