# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthLockUserModel do
  @moduledoc """
  Model for auth.lock_user stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_id: integer(),
    is_active: boolean(),
    is_locked: boolean()
  }

  @fields [:user_id, :is_active, :is_locked]

  @enforce_keys @fields
  defstruct @fields
end