# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetOutboundApiKeySecretByIdModel do
  @moduledoc """
  Model for auth.get_outbound_api_key_secret_by_id stored procedure result.
  """

  @type t() :: %__MODULE__{
    api_key_id: integer(),
    service_code: String.t(),
    service_url: String.t(),
    encrypted_secret: binary(),
    extra_data: map() | list()
  }

  @fields [:api_key_id, :service_code, :service_url, :encrypted_secret, :extra_data]

  @enforce_keys @fields
  defstruct @fields
end