# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthDeleteProviderModel do
  @moduledoc """
  Model for auth.delete_provider stored procedure result.
  """

  @type t() :: %__MODULE__{
    delete_provider: integer()
  }

  @fields [:delete_provider]

  @enforce_keys @fields
  defstruct @fields
end