# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetProvidersModel do
  @moduledoc """
  Model for auth.get_providers stored procedure result.
  """

  @type t() :: %__MODULE__{
    provider_id: integer(),
    code: String.t(),
    name: String.t(),
    is_active: boolean(),
    allows_group_mapping: boolean(),
    allows_group_sync: boolean()
  }

  @fields [:provider_id, :code, :name, :is_active, :allows_group_mapping, :allows_group_sync]

  @enforce_keys @fields
  defstruct @fields
end