# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreatePermSetPermissionsModel do
  @moduledoc """
  Model for auth.create_perm_set_permissions stored procedure result.
  """

  @type t() :: %__MODULE__{
    perm_set_id: integer(),
    perm_set_code: String.t(),
    permission_id: integer(),
    permission_code: String.t()
  }

  @fields [:perm_set_id, :perm_set_code, :permission_id, :permission_code]

  @enforce_keys @fields
  defstruct @fields
end