# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdateUserPasswordModel do
  @moduledoc """
  Model for auth.update_user_password stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_id: integer(),
    provider_code: String.t(),
    provider_uid: String.t()
  }

  @fields [:user_id, :provider_code, :provider_uid]

  @enforce_keys @fields
  defstruct @fields
end