# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetResourceAccessMatrixModel do
  @moduledoc """
  Model for auth.get_resource_access_matrix stored procedure result.
  """

  @type t() :: %__MODULE__{
    resource_type: String.t(),
    access_flag: String.t(),
    source: String.t()
  }

  @fields [:resource_type, :access_flag, :source]

  @enforce_keys @fields
  defstruct @fields
end