# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthFilterAccessibleResourcesModel do
  @moduledoc """
  Model for auth.filter_accessible_resources stored procedure result.
  """

  @type t() :: %__MODULE__{
    filter_accessible_resources: integer()
  }

  @fields [:filter_accessible_resources]

  @enforce_keys @fields
  defstruct @fields
end