# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdateUserLastSelectedTenantModel do
  @moduledoc """
  Model for auth.update_user_last_selected_tenant stored procedure result.
  """

  @type t() :: %__MODULE__{
    used_id: integer(),
    tenant_id: integer()
  }

  @fields [:used_id, :tenant_id]

  @enforce_keys @fields
  defstruct @fields
end