# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthAddUserToDefaultGroupsModel do
  @moduledoc """
  Model for auth.add_user_to_default_groups stored procedure result.
  """

  @type t() :: %__MODULE__{
          user_id: integer(),
          user_group_id: integer(),
          user_group_code: String.t(),
          user_group_title: String.t()
        }

  @fields [:user_id, :user_group_id, :user_group_code, :user_group_title]

  @enforce_keys @fields
  defstruct @fields
end
