# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthResetMfaModel do
  @moduledoc """
  Model for auth.reset_mfa stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_mfa_id: integer(),
    recovery_codes: list(String.t())
  }

  @fields [:user_mfa_id, :recovery_codes]

  @enforce_keys @fields
  defstruct @fields
end