# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthDeleteUserInfoModel do
  @moduledoc """
  Model for auth.delete_user_info stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_id: integer(),
    username: String.t()
  }

  @fields [:user_id, :username]

  @enforce_keys @fields
  defstruct @fields
end