# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateProviderModel do
  @moduledoc """
  Model for auth.create_provider stored procedure result.
  """

  @type t() :: %__MODULE__{
    create_provider: integer()
  }

  @fields [:create_provider]

  @enforce_keys @fields
  defstruct @fields
end