# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetResourceRoleAssignmentsModel do
  @moduledoc """
  Model for auth.get_resource_role_assignments stored procedure result.
  """

  @type t() :: %__MODULE__{
    resource_role_assignment_id: integer(),
    user_id: integer(),
    user_display_name: String.t(),
    user_group_id: integer(),
    group_title: String.t(),
    role_code: String.t(),
    role_title: String.t(),
    access_flags: list(String.t()),
    granted_by: integer(),
    granted_by_name: String.t(),
    created_at: DateTime.t()
  }

  @fields [:resource_role_assignment_id, :user_id, :user_display_name, :user_group_id, :group_title, :role_code, :role_title, :access_flags, :granted_by, :granted_by_name, :created_at]

  @enforce_keys @fields
  defstruct @fields
end