# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdatePermissionDataV17model do
  @moduledoc """
  Model for auth.update_permission_data_v1_7 stored procedure result.
  """

  @type t() :: %__MODULE__{
          update_permission_data_v17: integer()
        }

  @fields [:update_permission_data_v17]

  @enforce_keys @fields
  defstruct @fields
end
