# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdateProviderModel do
  @moduledoc """
  Model for auth.update_provider stored procedure result.
  """

  @type t() :: %__MODULE__{
    update_provider: integer()
  }

  @fields [:update_provider]

  @enforce_keys @fields
  defstruct @fields
end