# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGenerateApiKeyUsernameModel do
  @moduledoc """
  Model for auth.generate_api_key_username stored procedure result.
  """

  @type t() :: %__MODULE__{
    generate_api_key_username: String.t()
  }

  @fields [:generate_api_key_username]

  @enforce_keys @fields
  defstruct @fields
end