# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthDeleteBlacklistUserModel do
  @moduledoc """
  Model for auth.delete_blacklist_user stored procedure result.
  """

  @type t() :: %__MODULE__{
    removed_blacklist_id: integer(),
    username: String.t(),
    provider_code: String.t()
  }

  @fields [:removed_blacklist_id, :username, :provider_code]

  @enforce_keys @fields
  defstruct @fields
end