# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthDeleteProviderModel do
  @moduledoc """
  Model for auth.delete_provider stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_id: integer(),
    username: String.t(),
    display_name: String.t()
  }

  @fields [:user_id, :username, :display_name]

  @enforce_keys @fields
  defstruct @fields
end