# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthSearchUserEventsModel do
  @moduledoc """
  Model for auth.search_user_events stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_event_id: integer(),
    event_type_code: String.t(),
    requester_user_id: integer(),
    requester_username: String.t(),
    target_user_id: integer(),
    target_username: String.t(),
    target_user_oid: String.t(),
    ip_address: String.t(),
    user_agent: String.t(),
    origin: String.t(),
    event_data: map() | list(),
    correlation_id: String.t(),
    created_at: DateTime.t(),
    created_by: String.t(),
    total_items: integer()
  }

  @fields [:user_event_id, :event_type_code, :requester_user_id, :requester_username, :target_user_id, :target_username, :target_user_oid, :ip_address, :user_agent, :origin, :event_data, :correlation_id, :created_at, :created_by, :total_items]

  @enforce_keys @fields
  defstruct @fields
end