# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthIsMfaRequiredModel do
  @moduledoc """
  Model for auth.is_mfa_required stored procedure result.
  """

  @type t() :: %__MODULE__{
    is_mfa_required: boolean()
  }

  @fields [:is_mfa_required]

  @enforce_keys @fields
  defstruct @fields
end