# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdateApiKeySecretModel do
  @moduledoc """
  Model for auth.update_api_key_secret stored procedure result.
  """

  @type t() :: %__MODULE__{
    api_key_id: integer(),
    api_secret: String.t()
  }

  @fields [:api_key_id, :api_secret]

  @enforce_keys @fields
  defstruct @fields
end