# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnsureAccessFlagsModel do
  @moduledoc """
  Model for auth.ensure_access_flags stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    title: String.t(),
    source: String.t()
  }

  @fields [:code, :title, :source]

  @enforce_keys @fields
  defstruct @fields
end