# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdatePermissionDataV110model do
  @moduledoc """
  Model for auth.update_permission_data_v1_10 stored procedure result.
  """

  @type t() :: %__MODULE__{
          update_permission_data_v110: integer()
        }

  @fields [:update_permission_data_v110]

  @enforce_keys @fields
  defstruct @fields
end
