# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnsureUserGroupMappingsModel do
  @moduledoc """
  Model for auth.ensure_user_group_mappings stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    user_group_mapping_id: integer(),
    user_group_id: integer(),
    provider_code: String.t(),
    mapped_object_id: String.t(),
    mapped_object_name: String.t(),
    mapped_role: String.t()
  }

  @fields [:created_at, :created_by, :user_group_mapping_id, :user_group_id, :provider_code, :mapped_object_id, :mapped_object_name, :mapped_role]

  @enforce_keys @fields
  defstruct @fields
end