# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdateUserDataModel do
  @moduledoc """
  Model for auth.update_user_data stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_id: integer(),
    user_data_id: integer()
  }

  @fields [:user_id, :user_data_id]

  @enforce_keys @fields
  defstruct @fields
end