# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetInvitationsModel do
  @moduledoc """
  Model for auth.get_invitations stored procedure result.
  """

  @type t() :: %__MODULE__{
    invitation_id: integer(),
    uuid: String.t(),
    tenant_id: integer(),
    inviter_user_id: integer(),
    target_email: String.t(),
    target_user_id: integer(),
    status_code: String.t(),
    message: String.t(),
    template_code: String.t(),
    expires_at: DateTime.t(),
    accepted_at: DateTime.t(),
    rejected_at: DateTime.t(),
    revoked_at: DateTime.t(),
    created_at: DateTime.t(),
    created_by: String.t(),
    action_count: integer(),
    pending_actions: integer()
  }

  @fields [:invitation_id, :uuid, :tenant_id, :inviter_user_id, :target_email, :target_user_id, :status_code, :message, :template_code, :expires_at, :accepted_at, :rejected_at, :revoked_at, :created_at, :created_by, :action_count, :pending_actions]

  @enforce_keys @fields
  defstruct @fields
end