# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateTenantModel do
  @moduledoc """
  Model for auth.create_tenant stored procedure result.
  """

  @type t() :: %__MODULE__{
    tenant_id: integer(),
    uuid: String.t(),
    title: String.t(),
    code: String.t(),
    is_removable: boolean(),
    is_assignable: boolean(),
    access_type_code: String.t(),
    is_default: boolean()
  }

  @fields [:tenant_id, :uuid, :title, :code, :is_removable, :is_assignable, :access_type_code, :is_default]

  @enforce_keys @fields
  defstruct @fields
end