# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetResourceRoleFlagsModel do
  @moduledoc """
  Model for auth.get_resource_role_flags stored procedure result.
  """

  @type t() :: %__MODULE__{
    get_resource_role_flags: String.t()
  }

  @fields [:get_resource_role_flags]

  @enforce_keys @fields
  defstruct @fields
end