# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnrollMfaModel do
  @moduledoc """
  Model for auth.enroll_mfa stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_mfa_id: integer(),
    mfa_type_code: String.t(),
    recovery_codes: list(String.t()),
    enrolled_at: DateTime.t()
  }

  @fields [:user_mfa_id, :mfa_type_code, :recovery_codes, :enrolled_at]

  @enforce_keys @fields
  defstruct @fields
end