# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthProcessExternalGroupMemberSyncModel do
  @moduledoc """
  Model for auth.process_external_group_member_sync stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_group_id: integer(),
    user_group_mapping_id: integer(),
    state_code: String.t(),
    user_id: integer(),
    upn: String.t()
  }

  @fields [:user_group_id, :user_group_mapping_id, :state_code, :user_id, :upn]

  @enforce_keys @fields
  defstruct @fields
end