# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthSearchPermissionsModel do
  @moduledoc """
  Model for auth.search_permissions stored procedure result.
  """

  @type t() :: %__MODULE__{
    permission_id: integer(),
    title: String.t(),
    code: String.t(),
    full_code: String.t(),
    short_code: String.t(),
    is_assignable: boolean(),
    has_children: boolean(),
    source: String.t(),
    total_items: integer()
  }

  @fields [:permission_id, :title, :code, :full_code, :short_code, :is_assignable, :has_children, :source, :total_items]

  @enforce_keys @fields
  defstruct @fields
end