# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdateApiKeyModel do
  @moduledoc """
  Model for auth.update_api_key stored procedure result.
  """

  @type t() :: %__MODULE__{
    api_key_id: integer(),
    title: String.t(),
    description: String.t(),
    expire_at: DateTime.t(),
    notification_email: String.t()
  }

  @fields [:api_key_id, :title, :description, :expire_at, :notification_email]

  @enforce_keys @fields
  defstruct @fields
end