# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthRevokeResourceRoleModel do
  @moduledoc """
  Model for auth.revoke_resource_role stored procedure result.
  """

  @type t() :: %__MODULE__{
    revoke_resource_role: integer()
  }

  @fields [:revoke_resource_role]

  @enforce_keys @fields
  defstruct @fields
end