# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthIsOwnerModel do
  @moduledoc """
  Model for auth.is_owner stored procedure result.
  """

  @type t() :: %__MODULE__{
    is_owner: boolean()
  }

  @fields [:is_owner]

  @enforce_keys @fields
  defstruct @fields
end