# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthDeleteUserGroupModel do
  @moduledoc """
  Model for auth.delete_user_group stored procedure result.
  """

  @type t() :: %__MODULE__{
    delete_user_group: integer()
  }

  @fields [:delete_user_group]

  @enforce_keys @fields
  defstruct @fields
end