# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserAvailableTenantsModel do
  @moduledoc """
  Model for auth.get_user_available_tenants stored procedure result.
  """

  @type t() :: %__MODULE__{
    tenant_id: integer(),
    tenant_uuid: String.t(),
    tenant_code: String.t(),
    tenant_title: String.t(),
    tenant_is_default: boolean()
  }

  @fields [:tenant_id, :tenant_uuid, :tenant_code, :tenant_title, :tenant_is_default]

  @enforce_keys @fields
  defstruct @fields
end