# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnableProviderModel do
  @moduledoc """
  Model for auth.enable_provider stored procedure result.
  """

  @type t() :: %__MODULE__{
    enable_provider: integer()
  }

  @fields [:enable_provider]

  @enforce_keys @fields
  defstruct @fields
end