# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetResourceTypesModel do
  @moduledoc """
  Model for auth.get_resource_types stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    title: String.t(),
    full_title: String.t(),
    description: String.t(),
    is_active: boolean(),
    source: String.t(),
    parent_code: String.t(),
    path: String.t()
  }

  @fields [:code, :title, :full_title, :description, :is_active, :source, :parent_code, :path]

  @enforce_keys @fields
  defstruct @fields
end