# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthDisableUserIdentityModel do
  @moduledoc """
  Model for auth.disable_user_identity stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_identity_id: integer(),
    is_active: boolean()
  }

  @fields [:user_identity_id, :is_active]

  @enforce_keys @fields
  defstruct @fields
end