# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnsurePermSetsModel do
  @moduledoc """
  Model for auth.ensure_perm_sets stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    perm_set_id: integer(),
    tenant_id: integer(),
    code: String.t(),
    is_system: boolean(),
    is_assignable: boolean(),
    source: String.t()
  }

  @fields [:created_at, :created_by, :updated_at, :updated_by, :perm_set_id, :tenant_id, :code, :is_system, :is_assignable, :source]

  @enforce_keys @fields
  defstruct @fields
end