# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserGroupByIdModel do
  @moduledoc """
  Model for auth.get_user_group_by_id stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_group_id: integer(),
    tenant_id: integer(),
    title: String.t(),
    code: String.t(),
    is_system: boolean(),
    is_external: boolean(),
    is_assignable: boolean(),
    is_active: boolean(),
    is_default: boolean()
  }

  @fields [:user_group_id, :tenant_id, :title, :code, :is_system, :is_external, :is_assignable, :is_active, :is_default]

  @enforce_keys @fields
  defstruct @fields
end