# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdateUserPreferencesModel do
  @moduledoc """
  Model for auth.update_user_preferences stored procedure result.
  """

  @type t() :: %__MODULE__{
    updated_at: DateTime.t(),
    updated_by: String.t()
  }

  @fields [:updated_at, :updated_by]

  @enforce_keys @fields
  defstruct @fields
end