# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateInvitationModel do
  @moduledoc """
  Model for auth.create_invitation stored procedure result.
  """

  @type t() :: %__MODULE__{
    invitation_id: integer(),
    uuid: String.t(),
    on_create_actions: map() | list()
  }

  @fields [:invitation_id, :uuid, :on_create_actions]

  @enforce_keys @fields
  defstruct @fields
end