# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserByEmailForAuthenticationModel do
  @moduledoc """
  Model for auth.get_user_by_email_for_authentication stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_id: integer(),
    code: String.t(),
    uuid: String.t(),
    username: String.t(),
    email: String.t(),
    display_name: String.t(),
    provider: String.t(),
    password_hash: String.t(),
    password_salt: String.t()
  }

  @fields [:user_id, :code, :uuid, :username, :email, :display_name, :provider, :password_hash, :password_salt]

  @enforce_keys @fields
  defstruct @fields
end