# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthIsGroupMemberModel do
  @moduledoc """
  Model for auth.is_group_member stored procedure result.
  """

  @type t() :: %__MODULE__{
    is_group_member: boolean()
  }

  @fields [:is_group_member]

  @enforce_keys @fields
  defstruct @fields
end