# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserGroupsToSyncModel do
  @moduledoc """
  Model for auth.get_user_groups_to_sync stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_group_id: integer(),
    user_group_mapping_id: integer(),
    title: String.t(),
    code: String.t(),
    provider_code: String.t(),
    mapped_object_id: String.t(),
    mapped_object_name: String.t()
  }

  @fields [:user_group_id, :user_group_mapping_id, :title, :code, :provider_code, :mapped_object_id, :mapped_object_name]

  @enforce_keys @fields
  defstruct @fields
end