# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetMfaStatusModel do
  @moduledoc """
  Model for auth.get_mfa_status stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_mfa_id: integer(),
    mfa_type_code: String.t(),
    is_enabled: boolean(),
    is_confirmed: boolean(),
    enrolled_at: DateTime.t(),
    confirmed_at: DateTime.t(),
    recovery_codes_remaining: integer()
  }

  @fields [:user_mfa_id, :mfa_type_code, :is_enabled, :is_confirmed, :enrolled_at, :confirmed_at, :recovery_codes_remaining]

  @enforce_keys @fields
  defstruct @fields
end