# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetTenantMembersModel do
  @moduledoc """
  Model for auth.get_tenant_members stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_id: integer(),
    user_display_name: String.t(),
    user_code: String.t(),
    user_uuid: String.t(),
    user_tenant_groups: String.t()
  }

  @fields [:user_id, :user_display_name, :user_code, :user_uuid, :user_tenant_groups]

  @enforce_keys @fields
  defstruct @fields
end