# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetPermSetsModel do
  @moduledoc """
  Model for auth.get_perm_sets stored procedure result.
  """

  @type t() :: %__MODULE__{
    perm_set_id: integer(),
    title: String.t(),
    code: String.t(),
    is_system: boolean(),
    is_assignable: boolean(),
    permissions: map() | list(),
    source: String.t()
  }

  @fields [:perm_set_id, :title, :code, :is_system, :is_assignable, :permissions, :source]

  @enforce_keys @fields
  defstruct @fields
end