# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthLockUserGroupModel do
  @moduledoc """
  Model for auth.lock_user_group stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_group_id: integer(),
    is_active: boolean(),
    is_assignable: boolean(),
    updated_at: DateTime.t(),
    updated_by: String.t()
  }

  @fields [:user_group_id, :is_active, :is_assignable, :updated_at, :updated_by]

  @enforce_keys @fields
  defstruct @fields
end