# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateOwnerModel do
  @moduledoc """
  Model for auth.create_owner stored procedure result.
  """

  @type t() :: %__MODULE__{
    create_owner: integer()
  }

  @fields [:create_owner]

  @enforce_keys @fields
  defstruct @fields
end