# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnsureResourceTypesModel do
  @moduledoc """
  Model for auth.ensure_resource_types stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    title: String.t(),
    full_title: String.t() | nil,
    description: String.t() | nil,
    is_active: boolean(),
    source: String.t() | nil,
    parent_code: String.t() | nil,
    path: String.t(),
    key_schema: map() | list()
  }

  @fields [:code, :title, :full_title, :description, :is_active, :source, :parent_code, :path, :key_schema]

  @enforce_keys @fields
  defstruct @fields
end