# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateMfaPolicyModel do
  @moduledoc """
  Model for auth.create_mfa_policy stored procedure result.
  """

  @type t() :: %__MODULE__{
    create_mfa_policy: integer()
  }

  @fields [:create_mfa_policy]

  @enforce_keys @fields
  defstruct @fields
end