# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthValidateApiKeyModel do
  @moduledoc """
  Model for auth.validate_api_key stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_id: integer(),
    username: String.t(),
    user_display_name: String.t(),
    permission_full_codes: list(String.t())
  }

  @fields [:user_id, :username, :user_display_name, :permission_full_codes]

  @enforce_keys @fields
  defstruct @fields
end