# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetSysParamModel do
  @moduledoc """
  Model for auth.get_sys_param stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    sys_param_id: integer(),
    group_code: String.t(),
    code: String.t(),
    text_value: String.t() | nil,
    number_value: integer() | nil,
    bool_value: boolean() | nil
  }

  @fields [:created_at, :created_by, :updated_at, :updated_by, :sys_param_id, :group_code, :code, :text_value, :number_value, :bool_value]

  @enforce_keys @fields
  defstruct @fields
end