# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthSearchUserGroupsModel do
  @moduledoc """
  Model for auth.search_user_groups stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_group_id: integer(),
    title: String.t(),
    code: String.t(),
    is_system: boolean(),
    is_external: boolean(),
    is_assignable: boolean(),
    is_active: boolean(),
    is_default: boolean(),
    member_count: integer(),
    total_items: integer()
  }

  @fields [:user_group_id, :title, :code, :is_system, :is_external, :is_assignable, :is_active, :is_default, :member_count, :total_items]

  @enforce_keys @fields
  defstruct @fields
end