# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGenerateApiSecretHashModel do
  @moduledoc """
  Model for auth.generate_api_secret_hash stored procedure result.
  """

  @type t() :: %__MODULE__{
    generate_api_secret_hash: binary()
  }

  @fields [:generate_api_secret_hash]

  @enforce_keys @fields
  defstruct @fields
end