# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateUserEventModel do
  @moduledoc """
  Model for auth.create_user_event stored procedure result.
  """

  @type t() :: %__MODULE__{
    create_user_event: integer()
  }

  @fields [:create_user_event]

  @enforce_keys @fields
  defstruct @fields
end