# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnsureResourceRolesModel do
  @moduledoc """
  Model for auth.ensure_resource_roles stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    resource_type: String.t(),
    title: String.t(),
    description: String.t(),
    is_active: boolean(),
    source: String.t(),
    access_flags: list(String.t())
  }

  @fields [:code, :resource_type, :title, :description, :is_active, :source, :access_flags]

  @enforce_keys @fields
  defstruct @fields
end