# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateResourceTypeModel do
  @moduledoc """
  Model for auth.create_resource_type stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    title: String.t(),
    description: String.t() | nil,
    is_active: boolean(),
    source: String.t() | nil,
    parent_code: String.t() | nil,
    path: String.t()
  }

  @fields [:code, :title, :description, :is_active, :source, :parent_code, :path]

  @enforce_keys @fields
  defstruct @fields
end