# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserAssignedPermissionsModel do
  @moduledoc """
  Model for auth.get_user_assigned_permissions stored procedure result.
  """

  @type t() :: %__MODULE__{
    permissions: map() | list(),
    perm_set_title: String.t(),
    perm_set_id: integer(),
    perm_set_code: String.t(),
    assignment_id: integer(),
    user_group_id: integer()
  }

  @fields [:permissions, :perm_set_title, :perm_set_id, :perm_set_code, :assignment_id, :user_group_id]

  @enforce_keys @fields
  defstruct @fields
end