# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthIsBlacklistedModel do
  @moduledoc """
  Model for auth.is_blacklisted stored procedure result.
  """

  @type t() :: %__MODULE__{
    is_blacklisted: boolean()
  }

  @fields [:is_blacklisted]

  @enforce_keys @fields
  defstruct @fields
end