# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetTenantByIdModel do
  @moduledoc """
  Model for auth.get_tenant_by_id stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    tenant_id: integer(),
    uuid: String.t(),
    title: String.t(),
    code: String.t(),
    is_removable: boolean(),
    is_assignable: boolean()
  }

  @fields [:created_at, :created_by, :updated_at, :updated_by, :tenant_id, :uuid, :title, :code, :is_removable, :is_assignable]

  @enforce_keys @fields
  defstruct @fields
end