# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateTokenModel do
  @moduledoc """
  Model for auth.create_token stored procedure result.
  """

  @type t() :: %__MODULE__{
    token_id: integer(),
    token_uid: String.t(),
    expires_at: DateTime.t()
  }

  @fields [:token_id, :token_uid, :expires_at]

  @enforce_keys @fields
  defstruct @fields
end