# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetResourceAccessFlagsModel do
  @moduledoc """
  Model for auth.get_resource_access_flags stored procedure result.
  """

  @type t() :: %__MODULE__{
    access_flag: String.t(),
    source: String.t()
  }

  @fields [:access_flag, :source]

  @enforce_keys @fields
  defstruct @fields
end