# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthHasResourceAccessModel do
  @moduledoc """
  Model for auth.has_resource_access stored procedure result.
  """

  @type t() :: %__MODULE__{
    has_resource_access: boolean()
  }

  @fields [:has_resource_access]

  @enforce_keys @fields
  defstruct @fields
end