# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserGroupMembersModel do
  @moduledoc """
  Model for auth.get_user_group_members stored procedure result.
  """

  @type t() :: %__MODULE__{
    created: DateTime.t(),
    created_by: String.t(),
    member_id: integer(),
    member_type_code: String.t(),
    user_id: integer(),
    user_display_name: String.t(),
    user_is_system: boolean(),
    user_is_active: boolean(),
    user_is_locked: boolean(),
    mapping_id: integer(),
    mapping_mapped_object_name: String.t(),
    mapping_provider_code: String.t()
  }

  @fields [:created, :created_by, :member_id, :member_type_code, :user_id, :user_display_name, :user_is_system, :user_is_active, :user_is_locked, :mapping_id, :mapping_mapped_object_name, :mapping_provider_code]

  @enforce_keys @fields
  defstruct @fields
end