# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnsurePermissionsModel do
  @moduledoc """
  Model for auth.ensure_permissions stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    permission_id: integer(),
    is_assignable: boolean(),
    code: String.t(),
    full_code: String.t(),
    node_path: String.t(),
    has_children: boolean(),
    short_code: String.t(),
    source: String.t()
  }

  @fields [:created_at, :created_by, :updated_at, :updated_by, :permission_id, :is_assignable, :code, :full_code, :node_path, :has_children, :short_code, :source]

  @enforce_keys @fields
  defstruct @fields
end