# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthDeleteUserInfoModel do
  @moduledoc """
  Model for auth.delete_user_info stored procedure result.
  """

  @type t() :: %__MODULE__{
    delete_user_info: integer()
  }

  @fields [:delete_user_info]

  @enforce_keys @fields
  defstruct @fields
end