# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreatePermissionModel do
  @moduledoc """
  Model for auth.create_permission stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    permission_id: integer(),
    is_assignable: boolean(),
    title: String.t(),
    code: String.t() | nil,
    full_code: String.t() | nil,
    node_path: String.t() | nil,
    has_children: boolean(),
    full_title: String.t() | nil,
    nrm_search_data: String.t() | nil,
    short_code: String.t() | nil
  }

  @fields [:created_at, :created_by, :updated_at, :updated_by, :permission_id, :is_assignable, :title, :code, :full_code, :node_path, :has_children, :full_title, :nrm_search_data, :short_code]

  @enforce_keys @fields
  defstruct @fields
end