# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserByProviderOidModel do
  @moduledoc """
  Model for auth.get_user_by_provider_oid stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_id: integer(),
    code: String.t(),
    uuid: String.t(),
    username: String.t(),
    email: String.t(),
    display_name: String.t()
  }

  @fields [:user_id, :code, :uuid, :username, :email, :display_name]

  @enforce_keys @fields
  defstruct @fields
end