# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGenerateApiSecretModel do
  @moduledoc """
  Model for auth.generate_api_secret stored procedure result.
  """

  @type t() :: %__MODULE__{
    generate_api_secret: String.t()
  }

  @fields [:generate_api_secret]

  @enforce_keys @fields
  defstruct @fields
end