# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateUserTenantPreferencesModel do
  @moduledoc """
  Model for auth.create_user_tenant_preferences stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t()
  }

  @fields [:created_at, :created_by]

  @enforce_keys @fields
  defstruct @fields
end