# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthRevokeResourceAccessModel do
  @moduledoc """
  Model for auth.revoke_resource_access stored procedure result.
  """

  @type t() :: %__MODULE__{
    revoke_resource_access: integer()
  }

  @fields [:revoke_resource_access]

  @enforce_keys @fields
  defstruct @fields
end