# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthRevokeAllResourceRolesModel do
  @moduledoc """
  Model for auth.revoke_all_resource_roles stored procedure result.
  """

  @type t() :: %__MODULE__{
    revoke_all_resource_roles: integer()
  }

  @fields [:revoke_all_resource_roles]

  @enforce_keys @fields
  defstruct @fields
end