# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthHasOwnerModel do
  @moduledoc """
  Model for auth.has_owner stored procedure result.
  """

  @type t() :: %__MODULE__{
    has_owner: boolean()
  }

  @fields [:has_owner]

  @enforce_keys @fields
  defstruct @fields
end