# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUpdateUserGroupModel do
  @moduledoc """
  Model for auth.update_user_group stored procedure result.
  """

  @type t() :: %__MODULE__{
    update_user_group: integer()
  }

  @fields [:update_user_group]

  @enforce_keys @fields
  defstruct @fields
end