# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthUnassignApiKeyPermissionsModel do
  @moduledoc """
  Model for auth.unassign_api_key_permissions stored procedure result.
  """

  @type t() :: %__MODULE__{
    assignment_id: integer(),
    perm_set_id: integer(),
    perm_set_code: String.t(),
    perm_set_title: String.t(),
    permission_full_code: String.t(),
    permission_full_title: String.t(),
    permission_title: String.t()
  }

  @fields [:assignment_id, :perm_set_id, :perm_set_code, :perm_set_title, :permission_full_code, :permission_full_title, :permission_title]

  @enforce_keys @fields
  defstruct @fields
end