# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthSearchUsersModel do
  @moduledoc """
  Model for auth.search_users stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_id: integer(),
    code: String.t(),
    uuid: String.t(),
    username: String.t(),
    email: String.t(),
    display_name: String.t(),
    user_type_code: String.t(),
    is_active: boolean(),
    is_locked: boolean(),
    total_items: integer()
  }

  @fields [:user_id, :code, :uuid, :username, :email, :display_name, :user_type_code, :is_active, :is_locked, :total_items]

  @enforce_keys @fields
  defstruct @fields
end