# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCanManageUserGroupModel do
  @moduledoc """
  Model for auth.can_manage_user_group stored procedure result.
  """

  @type t() :: %__MODULE__{
    can_manage_user_group: boolean()
  }

  @fields [:can_manage_user_group]

  @enforce_keys @fields
  defstruct @fields
end