# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnsureUserGroupsModel do
  @moduledoc """
  Model for auth.ensure_user_groups stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    user_group_id: integer(),
    tenant_id: integer(),
    title: String.t(),
    code: String.t(),
    is_system: boolean(),
    is_external: boolean(),
    is_assignable: boolean(),
    is_active: boolean(),
    is_default: boolean(),
    can_members_manage_others: boolean(),
    can_members_see_others: boolean(),
    is_synced: boolean(),
    create_missing_users_on_sync: boolean(),
    source: String.t()
  }

  @fields [:created_at, :created_by, :updated_at, :updated_by, :user_group_id, :tenant_id, :title, :code, :is_system, :is_external, :is_assignable, :is_active, :is_default, :can_members_manage_others, :can_members_see_others, :is_synced, :create_missing_users_on_sync, :source]

  @enforce_keys @fields
  defstruct @fields
end