# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetOutboundApiKeyByIdModel do
  @moduledoc """
  Model for auth.get_outbound_api_key_by_id stored procedure result.
  """

  @type t() :: %__MODULE__{
    api_key_id: integer(),
    api_key: String.t(),
    title: String.t(),
    description: String.t(),
    service_code: String.t(),
    service_url: String.t(),
    extra_data: map() | list(),
    expire_at: DateTime.t(),
    notification_email: String.t(),
    created_at: DateTime.t(),
    updated_at: DateTime.t()
  }

  @fields [:api_key_id, :api_key, :title, :description, :service_code, :service_url, :extra_data, :expire_at, :notification_email, :created_at, :updated_at]

  @enforce_keys @fields
  defstruct @fields
end