# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthDeleteOutboundApiKeyModel do
  @moduledoc """
  Model for auth.delete_outbound_api_key stored procedure result.
  """

  @type t() :: %__MODULE__{
    api_key_id: integer(),
    service_code: String.t()
  }

  @fields [:api_key_id, :service_code]

  @enforce_keys @fields
  defstruct @fields
end