# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserAuditTrailModel do
  @moduledoc """
  Model for auth.get_user_audit_trail stored procedure result.
  """

  @type t() :: %__MODULE__{
    source: String.t(),
    event_id: integer(),
    event_type_code: String.t(),
    event_category: String.t(),
    message: String.t(),
    request_context: map() | list(),
    event_data: map() | list(),
    correlation_id: String.t(),
    created_at: DateTime.t(),
    created_by: String.t(),
    total_items: integer()
  }

  @fields [:source, :event_id, :event_type_code, :event_category, :message, :request_context, :event_data, :correlation_id, :created_at, :created_by, :total_items]

  @enforce_keys @fields
  defstruct @fields
end