# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetTenantUsersModel do
  @moduledoc """
  Model for auth.get_tenant_users stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_id: integer(),
    username: String.t(),
    display_name: String.t(),
    user_groups: list(String.t())
  }

  @fields [:user_id, :username, :display_name, :user_groups]

  @enforce_keys @fields
  defstruct @fields
end