# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthSetPermissionAsAssignableModel do
  @moduledoc """
  Model for auth.set_permission_as_assignable stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    assignment_id: integer(),
    tenant_id: integer() | nil,
    user_group_id: integer() | nil,
    user_id: integer() | nil,
    perm_set_id: integer() | nil,
    permission_id: integer() | nil
  }

  @fields [:created_at, :created_by, :assignment_id, :tenant_id, :user_group_id, :user_id, :perm_set_id, :permission_id]

  @enforce_keys @fields
  defstruct @fields
end