# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthDeleteApiKeyModel do
  @moduledoc """
  Model for auth.delete_api_key stored procedure result.
  """

  @type t() :: %__MODULE__{
    delete_api_key: integer()
  }

  @fields [:delete_api_key]

  @enforce_keys @fields
  defstruct @fields
end