# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateInvitationTemplateModel do
  @moduledoc """
  Model for auth.create_invitation_template stored procedure result.
  """

  @type t() :: %__MODULE__{
    create_invitation_template: integer()
  }

  @fields [:create_invitation_template]

  @enforce_keys @fields
  defstruct @fields
end