# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUsersGroupsAndPermissionsModel do
  @moduledoc """
  Model for auth.get_users_groups_and_permissions stored procedure result.
  """

  @type t() :: %__MODULE__{
    tenant_id: integer(),
    tenant_uuid: String.t(),
    groups: list(String.t()),
    permissions: list(String.t()),
    short_code_permissions: list(String.t())
  }

  @fields [:tenant_id, :tenant_uuid, :groups, :permissions, :short_code_permissions]

  @enforce_keys @fields
  defstruct @fields
end