# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateUserGroupModel do
  @moduledoc """
  Model for auth.create_user_group stored procedure result.
  """

  @type t() :: %__MODULE__{
    create_user_group: integer()
  }

  @fields [:create_user_group]

  @enforce_keys @fields
  defstruct @fields
end