# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthSearchTenantsModel do
  @moduledoc """
  Model for auth.search_tenants stored procedure result.
  """

  @type t() :: %__MODULE__{
    tenant_id: integer(),
    uuid: String.t(),
    title: String.t(),
    code: String.t(),
    is_removable: boolean(),
    is_assignable: boolean(),
    total_items: integer()
  }

  @fields [:tenant_id, :uuid, :title, :code, :is_removable, :is_assignable, :total_items]

  @enforce_keys @fields
  defstruct @fields
end