# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserPermissionsModel do
  @moduledoc """
  Model for auth.get_user_permissions stored procedure result.
  """

  @type t() :: %__MODULE__{
    assignment_id: integer(),
    perm_set_code: String.t(),
    perm_set_title: String.t(),
    user_group_member_id: integer(),
    user_group_title: String.t(),
    permission_inheritance_type: String.t(),
    permission_full_code: String.t(),
    permission_title: String.t(),
    tenant_id: integer(),
    tenant_code: String.t(),
    tenant_title: String.t()
  }

  @fields [:assignment_id, :perm_set_code, :perm_set_title, :user_group_member_id, :user_group_title, :permission_inheritance_type, :permission_full_code, :permission_title, :tenant_id, :tenant_code, :tenant_title]

  @enforce_keys @fields
  defstruct @fields
end