# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthAssignResourceRoleModel do
  @moduledoc """
  Model for auth.assign_resource_role stored procedure result.
  """

  @type t() :: %__MODULE__{
    resource_role_assignment_id: integer(),
    role_code: String.t()
  }

  @fields [:resource_role_assignment_id, :role_code]

  @enforce_keys @fields
  defstruct @fields
end