# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetMfaPoliciesModel do
  @moduledoc """
  Model for auth.get_mfa_policies stored procedure result.
  """

  @type t() :: %__MODULE__{
    mfa_policy_id: integer(),
    tenant_id: integer(),
    user_group_id: integer(),
    user_id: integer(),
    mfa_required: boolean(),
    created_at: DateTime.t(),
    created_by: String.t()
  }

  @fields [:mfa_policy_id, :tenant_id, :user_group_id, :user_id, :mfa_required, :created_at, :created_by]

  @enforce_keys @fields
  defstruct @fields
end