# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserDataModel do
  @moduledoc """
  Model for auth.get_user_data stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    user_data_id: integer(),
    user_id: integer(),
    first_name: String.t(),
    middle_name: String.t(),
    last_name: String.t(),
    settings: map() | list(),
    preferences: map() | list(),
    custom_data: map() | list()
  }

  @fields [:created_at, :created_by, :updated_at, :updated_by, :user_data_id, :user_id, :first_name, :middle_name, :last_name, :settings, :preferences, :custom_data]

  @enforce_keys @fields
  defstruct @fields
end