# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthDeleteTenantByUuidModel do
  @moduledoc """
  Model for auth.delete_tenant_by_uuid stored procedure result.
  """

  @type t() :: %__MODULE__{
    tenant_id: integer(),
    uuid: String.t(),
    code: String.t()
  }

  @fields [:tenant_id, :uuid, :code]

  @enforce_keys @fields
  defstruct @fields
end