# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthEnsureResourceTypeFlagsModel do
  @moduledoc """
  Model for auth.ensure_resource_type_flags stored procedure result.
  """

  @type t() :: %__MODULE__{
    resource_type_code: String.t(),
    access_flag_code: String.t()
  }

  @fields [:resource_type_code, :access_flag_code]

  @enforce_keys @fields
  defstruct @fields
end