# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGetUserIdentityModel do
  @moduledoc """
  Model for auth.get_user_identity stored procedure result.
  """

  @type t() :: %__MODULE__{
    user_identity_id: integer(),
    provider_code: String.t(),
    uid: String.t(),
    user_id: integer(),
    provider_groups: list(String.t()),
    provider_roles: list(String.t()),
    user_data: map() | list()
  }

  @fields [:user_identity_id, :provider_code, :uid, :user_id, :provider_groups, :provider_roles, :user_data]

  @enforce_keys @fields
  defstruct @fields
end