# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthCreateOutboundApiKeyModel do
  @moduledoc """
  Model for auth.create_outbound_api_key stored procedure result.
  """

  @type t() :: %__MODULE__{
    api_key_id: integer(),
    api_key: String.t(),
    service_code: String.t()
  }

  @fields [:api_key_id, :api_key, :service_code]

  @enforce_keys @fields
  defstruct @fields
end