# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthSetTokenAsUsedModel do
  @moduledoc """
  Model for auth.set_token_as_used stored procedure result.
  """

  @type t() :: %__MODULE__{
    token_id: integer(),
    token_uid: String.t(),
    token_state_code: String.t(),
    used_at: DateTime.t(),
    user_id: integer(),
    user_oid: String.t(),
    token_data: map() | list()
  }

  @fields [:token_id, :token_uid, :token_state_code, :used_at, :user_id, :user_oid, :token_data]

  @enforce_keys @fields
  defstruct @fields
end