# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthDisableProviderModel do
  @moduledoc """
  Model for auth.disable_provider stored procedure result.
  """

  @type t() :: %__MODULE__{
    disable_provider: integer()
  }

  @fields [:disable_provider]

  @enforce_keys @fields
  defstruct @fields
end