# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.AuthGrantResourceAccessModel do
  @moduledoc """
  Model for auth.grant_resource_access stored procedure result.
  """

  @type t() :: %__MODULE__{
    resource_access_id: integer(),
    access_flag: String.t()
  }

  @fields [:resource_access_id, :access_flag]

  @enforce_keys @fields
  defstruct @fields
end