# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.CopyTranslationsModel do
  @moduledoc """
  Model for public.copy_translations stored procedure result.
  """

  @type t() :: %__MODULE__{
    operation: String.t(),
    count: integer()
  }

  @fields [:operation, :count]

  @enforce_keys @fields
  defstruct @fields
end