# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.CreateTokenTypeModel do
  @moduledoc """
  Model for public.create_token_type stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    default_expiration_in_seconds: integer() | nil,
    is_system: boolean()
  }

  @fields [:code, :default_expiration_in_seconds, :is_system]

  @enforce_keys @fields
  defstruct @fields
end