# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.CreateJournalMessageForEntityModel do
  @moduledoc """
  Model for public.create_journal_message_for_entity stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    correlation_id: String.t(),
    journal_id: integer(),
    tenant_id: integer(),
    event_id: integer(),
    user_id: integer(),
    keys: map() | list(),
    data_payload: map() | list(),
    request_context: map() | list()
  }

  @fields [:created_at, :created_by, :correlation_id, :journal_id, :tenant_id, :event_id, :user_id, :keys, :data_payload, :request_context]

  @enforce_keys @fields
  defstruct @fields
end