# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.CreateTranslationModel do
  @moduledoc """
  Model for public.create_translation stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    translation_id: integer(),
    language_code: String.t(),
    tenant_id: integer(),
    data_group: String.t(),
    data_object_code: String.t(),
    data_object_id: integer(),
    context: String.t(),
    value: String.t()
  }

  @fields [:created_at, :created_by, :updated_at, :updated_by, :translation_id, :language_code, :tenant_id, :data_group, :data_object_code, :data_object_id, :context, :value]

  @enforce_keys @fields
  defstruct @fields
end