# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.CreateEventCategoryModel do
  @moduledoc """
  Model for public.create_event_category stored procedure result.
  """

  @type t() :: %__MODULE__{
    category_code: String.t(),
    range_start: integer(),
    range_end: integer(),
    is_error: boolean(),
    source: String.t()
  }

  @fields [:category_code, :range_start, :range_end, :is_error, :source]

  @enforce_keys @fields
  defstruct @fields
end