# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.CreateEventCodeModel do
  @moduledoc """
  Model for public.create_event_code stored procedure result.
  """

  @type t() :: %__MODULE__{
    event_id: integer(),
    code: String.t(),
    category_code: String.t(),
    is_read_only: boolean(),
    is_system: boolean(),
    source: String.t() | nil
  }

  @fields [:event_id, :code, :category_code, :is_read_only, :is_system, :source]

  @enforce_keys @fields
  defstruct @fields
end