# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.CreateJournalMessageByCodeModel do
  @moduledoc """
  Model for public.create_journal_message_by_code stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    correlation_id: String.t() | nil,
    journal_id: integer(),
    tenant_id: integer() | nil,
    event_id: integer(),
    user_id: integer() | nil,
    keys: map() | list() | nil,
    data_payload: map() | list() | nil,
    request_context: map() | list() | nil
  }

  @fields [:created_at, :created_by, :correlation_id, :journal_id, :tenant_id, :event_id, :user_id, :keys, :data_payload, :request_context]

  @enforce_keys @fields
  defstruct @fields
end