# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.CreateEventMessageModel do
  @moduledoc """
  Model for public.create_event_message stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    event_message_id: integer(),
    event_id: integer(),
    language_code: String.t(),
    message_template: String.t(),
    is_active: boolean()
  }

  @fields [:created_at, :created_by, :updated_at, :updated_by, :event_message_id, :event_id, :language_code, :message_template, :is_active]

  @enforce_keys @fields
  defstruct @fields
end