# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.FormatJournalMessageModel do
  @moduledoc """
  Model for public.format_journal_message stored procedure result.
  """

  @type t() :: %__MODULE__{
    format_journal_message: String.t()
  }

  @fields [:format_journal_message]

  @enforce_keys @fields
  defstruct @fields
end