# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.GetFrontendLanguagesModel do
  @moduledoc """
  Model for public.get_frontend_languages stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    value: String.t(),
    display_name: String.t(),
    frontend_logical_order: integer(),
    is_default_frontend: boolean(),
    custom_data: map() | list()
  }

  @fields [:code, :value, :display_name, :frontend_logical_order, :is_default_frontend, :custom_data]

  @enforce_keys @fields
  defstruct @fields
end