# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.GetDefaultLanguageModel do
  @moduledoc """
  Model for public.get_default_language stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    value: String.t(),
    display_name: String.t(),
    custom_data: map() | list()
  }

  @fields [:code, :value, :display_name, :custom_data]

  @enforce_keys @fields
  defstruct @fields
end