# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.GetCommunicationLanguagesModel do
  @moduledoc """
  Model for public.get_communication_languages stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    value: String.t(),
    display_name: String.t(),
    communication_logical_order: integer(),
    is_default_communication: boolean(),
    custom_data: map() | list()
  }

  @fields [:code, :value, :display_name, :communication_logical_order, :is_default_communication, :custom_data]

  @enforce_keys @fields
  defstruct @fields
end