# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.GetGroupTranslationsModel do
  @moduledoc """
  Model for public.get_group_translations stored procedure result.
  """

  @type t() :: %__MODULE__{
    get_group_translations: map() | list()
  }

  @fields [:get_group_translations]

  @enforce_keys @fields
  defstruct @fields
end