# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.GetJournalPayloadModel do
  @moduledoc """
  Model for public.get_journal_payload stored procedure result.
  """

  @type t() :: %__MODULE__{
    journal_id: integer(),
    payload: String.t()
  }

  @fields [:journal_id, :payload]

  @enforce_keys @fields
  defstruct @fields
end