# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.GetLanguagesModel do
  @moduledoc """
  Model for public.get_languages stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    value: String.t(),
    display_name: String.t(),
    is_frontend_language: boolean(),
    is_backend_language: boolean(),
    is_communication_language: boolean(),
    frontend_logical_order: integer(),
    backend_logical_order: integer(),
    communication_logical_order: integer(),
    is_default_frontend: boolean(),
    is_default_backend: boolean(),
    is_default_communication: boolean(),
    custom_data: map() | list()
  }

  @fields [:code, :value, :display_name, :is_frontend_language, :is_backend_language, :is_communication_language, :frontend_logical_order, :backend_logical_order, :communication_logical_order, :is_default_frontend, :is_default_backend, :is_default_communication, :custom_data]

  @enforce_keys @fields
  defstruct @fields
end