# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.GetPermissionsMapModel do
  @moduledoc """
  Model for public.get_permissions_map stored procedure result.
  """

  @type t() :: %__MODULE__{
    permission_id: integer(),
    full_code: String.t(),
    short_code: String.t(),
    title: String.t()
  }

  @fields [:permission_id, :full_code, :short_code, :title]

  @enforce_keys @fields
  defstruct @fields
end