# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.GetVersionModel do
  @moduledoc """
  Model for public.get_version stored procedure result.
  """

  @type t() :: %__MODULE__{
    version_id: integer(),
    version: String.t(),
    title: String.t(),
    execution_started: DateTime.t(),
    execution_finished: DateTime.t()
  }

  @fields [:version_id, :version, :title, :execution_started, :execution_finished]

  @enforce_keys @fields
  defstruct @fields
end