# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.GetEventMessageTemplateModel do
  @moduledoc """
  Model for public.get_event_message_template stored procedure result.
  """

  @type t() :: %__MODULE__{
    get_event_message_template: String.t()
  }

  @fields [:get_event_message_template]

  @enforce_keys @fields
  defstruct @fields
end