# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.GetJournalEntryModel do
  @moduledoc """
  Model for public.get_journal_entry stored procedure result.
  """

  @type t() :: %__MODULE__{
    journal_id: integer(),
    event_id: integer(),
    event_code: String.t(),
    event_category: String.t(),
    message: String.t(),
    keys: map() | list(),
    payload: map() | list(),
    created_at: DateTime.t(),
    created_by: String.t(),
    correlation_id: String.t()
  }

  @fields [:journal_id, :event_id, :event_code, :event_category, :message, :keys, :payload, :created_at, :created_by, :correlation_id]

  @enforce_keys @fields
  defstruct @fields
end