# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.GetBackendLanguagesModel do
  @moduledoc """
  Model for public.get_backend_languages stored procedure result.
  """

  @type t() :: %__MODULE__{
    code: String.t(),
    value: String.t(),
    display_name: String.t(),
    backend_logical_order: integer(),
    is_default_backend: boolean(),
    custom_data: map() | list()
  }

  @fields [:code, :value, :display_name, :backend_logical_order, :is_default_backend, :custom_data]

  @enforce_keys @fields
  defstruct @fields
end