# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.InternalResolveTenantModel do
  @moduledoc """
  Model for internal.resolve_tenant stored procedure result.
  """

  @type t() :: %__MODULE__{
    resolve_tenant: integer()
  }

  @fields [:resolve_tenant]

  @enforce_keys @fields
  defstruct @fields
end