# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.InternalResolveUserModel do
  @moduledoc """
  Model for internal.resolve_user stored procedure result.
  """

  @type t() :: %__MODULE__{
    resolve_user: integer()
  }

  @fields [:resolve_user]

  @enforce_keys @fields
  defstruct @fields
end