# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.InternalResolveGroupModel do
  @moduledoc """
  Model for internal.resolve_group stored procedure result.
  """

  @type t() :: %__MODULE__{
    resolve_group: integer()
  }

  @fields [:resolve_group]

  @enforce_keys @fields
  defstruct @fields
end