# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.JournalKeysModel do
  @moduledoc """
  Model for public.journal_keys stored procedure result.
  """

  @type t() :: %__MODULE__{
    journal_keys: map() | list()
  }

  @fields [:journal_keys]

  @enforce_keys @fields
  defstruct @fields
end