# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.PurgeAuditDataModel do
  @moduledoc """
  Model for public.purge_audit_data stored procedure result.
  """

  @type t() :: %__MODULE__{
    journal_deleted: integer(),
    user_events_deleted: integer()
  }

  @fields [:journal_deleted, :user_events_deleted]

  @enforce_keys @fields
  defstruct @fields
end