# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.SearchJournalModel do
  @moduledoc """
  Model for public.search_journal stored procedure result.
  """

  @type t() :: %__MODULE__{
    journal_id: integer(),
    event_id: integer(),
    event_code: String.t(),
    event_category: String.t(),
    user_id: integer(),
    message: String.t(),
    keys: map() | list(),
    created_at: DateTime.t(),
    created_by: String.t(),
    correlation_id: String.t(),
    total_items: integer()
  }

  @fields [:journal_id, :event_id, :event_code, :event_category, :user_id, :message, :keys, :created_at, :created_by, :correlation_id, :total_items]

  @enforce_keys @fields
  defstruct @fields
end