# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.SearchJournalMsgsModel do
  @moduledoc """
  Model for public.search_journal_msgs stored procedure result.
  """

  @type t() :: %__MODULE__{
    created: DateTime.t(),
    created_by: String.t(),
    journal_id: integer(),
    event_id: integer(),
    data_group: String.t(),
    data_object_id: integer(),
    data_object_code: String.t(),
    user_id: integer(),
    msg: String.t(),
    total_items: integer()
  }

  @fields [:created, :created_by, :journal_id, :event_id, :data_group, :data_object_id, :data_object_code, :user_id, :msg, :total_items]

  @enforce_keys @fields
  defstruct @fields
end