# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.SearchTranslationsModel do
  @moduledoc """
  Model for public.search_translations stored procedure result.
  """

  @type t() :: %__MODULE__{
    translation_id: integer(),
    language_code: String.t(),
    language_value: String.t(),
    data_group: String.t(),
    data_object_code: String.t(),
    data_object_id: integer(),
    value: String.t(),
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    total_items: integer()
  }

  @fields [:translation_id, :language_code, :language_value, :data_group, :data_object_code, :data_object_id, :value, :created_at, :created_by, :updated_at, :updated_by, :total_items]

  @enforce_keys @fields
  defstruct @fields
end