# Autogenerated using db-gen
# Changes to this file will be lost on next generation

defmodule KeenAuthPermissions.Database.Models.UpdateLanguageModel do
  @moduledoc """
  Model for public.update_language stored procedure result.
  """

  @type t() :: %__MODULE__{
    created_at: DateTime.t(),
    created_by: String.t(),
    updated_at: DateTime.t(),
    updated_by: String.t(),
    code: String.t(),
    value: String.t(),
    tenant_id: integer(),
    is_frontend_language: boolean(),
    is_backend_language: boolean(),
    is_communication_language: boolean(),
    frontend_logical_order: integer(),
    backend_logical_order: integer(),
    communication_logical_order: integer(),
    is_default_frontend: boolean(),
    is_default_backend: boolean(),
    is_default_communication: boolean(),
    custom_data: map() | list()
  }

  @fields [:created_at, :created_by, :updated_at, :updated_by, :code, :value, :tenant_id, :is_frontend_language, :is_backend_language, :is_communication_language, :frontend_logical_order, :backend_logical_order, :communication_logical_order, :is_default_frontend, :is_default_backend, :is_default_communication, :custom_data]

  @enforce_keys @fields
  defstruct @fields
end